/*
 * Generated by Bluespec Compiler, version 2014.05.C (build 33930, 2014-05-28)
 * 
 * On Thu May  3 20:09:22 IST 2018
 * 
 */
#include "bluesim_primitives.h"
#include "mkCsrBMVM.h"


/* String declarations */
static std::string const __str_literal_7("../CSR_BMVM/LUT/", 16u);
static std::string const __str_literal_1("../CSR_BMVM/LUT/nnz0.mem", 24u);
static std::string const __str_literal_2("../CSR_BMVM/LUT/row0.mem", 24u);
static std::string const __str_literal_3("ERROR: %m: mkBRAMSeverAdapter overrun", 37u);
static std::string const __str_literal_6("Request Recevived %s", 20u);
static std::string const __str_literal_5("Row Request", 11u);
static std::string const __str_literal_9("Row Response %0b", 16u);
static std::string const __str_literal_4("State 0", 7u);
static std::string const __str_literal_8("State 1", 7u);
static std::string const __str_literal_10("State 2", 7u);
static std::string const __str_literal_11("State 3", 7u);


/* Constructor */
MOD_mkCsrBMVM::MOD_mkCsrBMVM(tSimStateHdl simHdl,
			     char const *name,
			     Module *parent,
			     tUInt32 ARG_lut_num)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    PARAM_lut_num(ARG_lut_num),
    INST_in(simHdl, "in", this, 32u, 0u, (tUInt8)0u),
    INST_in_fifo(simHdl, "in_fifo", this, 32u, 2u, 1u, 0u),
    INST_lut_nnz_memory(simHdl,
			"lut_nnz_memory",
			this,
			__str_literal_1,
			(tUInt8)0u,
			6u,
			5u,
			(tUInt8)64u,
			(tUInt8)1u,
			1u),
    INST_lut_nnz_serverAdapter_cnt(simHdl,
				   "lut_nnz_serverAdapter_cnt",
				   this,
				   3u,
				   (tUInt8)0u,
				   (tUInt8)0u),
    INST_lut_nnz_serverAdapter_cnt_1(simHdl, "lut_nnz_serverAdapter_cnt_1", this, 3u, (tUInt8)0u),
    INST_lut_nnz_serverAdapter_cnt_2(simHdl, "lut_nnz_serverAdapter_cnt_2", this, 3u, (tUInt8)0u),
    INST_lut_nnz_serverAdapter_cnt_3(simHdl, "lut_nnz_serverAdapter_cnt_3", this, 3u, (tUInt8)0u),
    INST_lut_nnz_serverAdapter_outDataCore(simHdl,
					   "lut_nnz_serverAdapter_outDataCore",
					   this,
					   5u,
					   3u,
					   1u,
					   0u),
    INST_lut_nnz_serverAdapter_outData_deqCalled(simHdl,
						 "lut_nnz_serverAdapter_outData_deqCalled",
						 this,
						 0u),
    INST_lut_nnz_serverAdapter_outData_enqData(simHdl,
					       "lut_nnz_serverAdapter_outData_enqData",
					       this,
					       5u,
					       (tUInt8)0u),
    INST_lut_nnz_serverAdapter_outData_outData(simHdl,
					       "lut_nnz_serverAdapter_outData_outData",
					       this,
					       5u,
					       (tUInt8)0u),
    INST_lut_nnz_serverAdapter_s1(simHdl, "lut_nnz_serverAdapter_s1", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_lut_nnz_serverAdapter_s1_1(simHdl, "lut_nnz_serverAdapter_s1_1", this, 2u, (tUInt8)0u),
    INST_lut_nnz_serverAdapter_writeWithResp(simHdl,
					     "lut_nnz_serverAdapter_writeWithResp",
					     this,
					     2u,
					     (tUInt8)0u),
    INST_lut_row_memory(simHdl,
			"lut_row_memory",
			this,
			__str_literal_2,
			(tUInt8)0u,
			5u,
			6u,
			(tUInt8)32u,
			(tUInt8)1u,
			1u),
    INST_lut_row_serverAdapter_cnt(simHdl,
				   "lut_row_serverAdapter_cnt",
				   this,
				   3u,
				   (tUInt8)0u,
				   (tUInt8)0u),
    INST_lut_row_serverAdapter_cnt_1(simHdl, "lut_row_serverAdapter_cnt_1", this, 3u, (tUInt8)0u),
    INST_lut_row_serverAdapter_cnt_2(simHdl, "lut_row_serverAdapter_cnt_2", this, 3u, (tUInt8)0u),
    INST_lut_row_serverAdapter_cnt_3(simHdl, "lut_row_serverAdapter_cnt_3", this, 3u, (tUInt8)0u),
    INST_lut_row_serverAdapter_outDataCore(simHdl,
					   "lut_row_serverAdapter_outDataCore",
					   this,
					   6u,
					   3u,
					   1u,
					   0u),
    INST_lut_row_serverAdapter_outData_deqCalled(simHdl,
						 "lut_row_serverAdapter_outData_deqCalled",
						 this,
						 0u),
    INST_lut_row_serverAdapter_outData_enqData(simHdl,
					       "lut_row_serverAdapter_outData_enqData",
					       this,
					       6u,
					       (tUInt8)0u),
    INST_lut_row_serverAdapter_outData_outData(simHdl,
					       "lut_row_serverAdapter_outData_outData",
					       this,
					       6u,
					       (tUInt8)0u),
    INST_lut_row_serverAdapter_s1(simHdl, "lut_row_serverAdapter_s1", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_lut_row_serverAdapter_s1_1(simHdl, "lut_row_serverAdapter_s1_1", this, 2u, (tUInt8)0u),
    INST_lut_row_serverAdapter_writeWithResp(simHdl,
					     "lut_row_serverAdapter_writeWithResp",
					     this,
					     2u,
					     (tUInt8)0u),
    INST_nz_num(simHdl, "nz_num", this, 6u, (tUInt8)0u, (tUInt8)0u),
    INST_out(simHdl, "out", this, 32u, 0u, (tUInt8)0u),
    INST_out_fifo(simHdl, "out_fifo", this, 32u, 2u, 1u, 0u),
    INST_row_end(simHdl, "row_end", this, 6u, (tUInt8)0u, (tUInt8)0u),
    INST_row_num(simHdl, "row_num", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_row_start(simHdl, "row_start", this, 6u, (tUInt8)0u, (tUInt8)0u),
    INST_state(simHdl, "state", this, 2u, (tUInt8)0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 66u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkCsrBMVM::init_symbols_0()
{
  init_symbol(&symbols[0u], "b__h1524", SYM_DEF, &DEF_b__h1524, 3u);
  init_symbol(&symbols[1u], "b__h3084", SYM_DEF, &DEF_b__h3084, 3u);
  init_symbol(&symbols[2u], "in", SYM_MODULE, &INST_in);
  init_symbol(&symbols[3u], "in_fifo", SYM_MODULE, &INST_in_fifo);
  init_symbol(&symbols[4u], "lut_nnz_memory", SYM_MODULE, &INST_lut_nnz_memory);
  init_symbol(&symbols[5u], "lut_nnz_serverAdapter_cnt", SYM_MODULE, &INST_lut_nnz_serverAdapter_cnt);
  init_symbol(&symbols[6u],
	      "lut_nnz_serverAdapter_cnt_1",
	      SYM_MODULE,
	      &INST_lut_nnz_serverAdapter_cnt_1);
  init_symbol(&symbols[7u],
	      "lut_nnz_serverAdapter_cnt_2",
	      SYM_MODULE,
	      &INST_lut_nnz_serverAdapter_cnt_2);
  init_symbol(&symbols[8u],
	      "lut_nnz_serverAdapter_cnt_3",
	      SYM_MODULE,
	      &INST_lut_nnz_serverAdapter_cnt_3);
  init_symbol(&symbols[9u],
	      "lut_nnz_serverAdapter_outData_deqCalled",
	      SYM_MODULE,
	      &INST_lut_nnz_serverAdapter_outData_deqCalled);
  init_symbol(&symbols[10u],
	      "lut_nnz_serverAdapter_outData_enqData",
	      SYM_MODULE,
	      &INST_lut_nnz_serverAdapter_outData_enqData);
  init_symbol(&symbols[11u],
	      "lut_nnz_serverAdapter_outData_outData",
	      SYM_MODULE,
	      &INST_lut_nnz_serverAdapter_outData_outData);
  init_symbol(&symbols[12u],
	      "lut_nnz_serverAdapter_outDataCore",
	      SYM_MODULE,
	      &INST_lut_nnz_serverAdapter_outDataCore);
  init_symbol(&symbols[13u], "lut_nnz_serverAdapter_s1", SYM_MODULE, &INST_lut_nnz_serverAdapter_s1);
  init_symbol(&symbols[14u],
	      "lut_nnz_serverAdapter_s1_1",
	      SYM_MODULE,
	      &INST_lut_nnz_serverAdapter_s1_1);
  init_symbol(&symbols[15u],
	      "lut_nnz_serverAdapter_writeWithResp",
	      SYM_MODULE,
	      &INST_lut_nnz_serverAdapter_writeWithResp);
  init_symbol(&symbols[16u], "lut_num", SYM_PARAM, (void *)(&PARAM_lut_num), 32u);
  init_symbol(&symbols[17u], "lut_row_memory", SYM_MODULE, &INST_lut_row_memory);
  init_symbol(&symbols[18u],
	      "lut_row_serverAdapter_cnt",
	      SYM_MODULE,
	      &INST_lut_row_serverAdapter_cnt);
  init_symbol(&symbols[19u],
	      "lut_row_serverAdapter_cnt_1",
	      SYM_MODULE,
	      &INST_lut_row_serverAdapter_cnt_1);
  init_symbol(&symbols[20u],
	      "lut_row_serverAdapter_cnt_2",
	      SYM_MODULE,
	      &INST_lut_row_serverAdapter_cnt_2);
  init_symbol(&symbols[21u],
	      "lut_row_serverAdapter_cnt_3",
	      SYM_MODULE,
	      &INST_lut_row_serverAdapter_cnt_3);
  init_symbol(&symbols[22u],
	      "lut_row_serverAdapter_outData_deqCalled",
	      SYM_MODULE,
	      &INST_lut_row_serverAdapter_outData_deqCalled);
  init_symbol(&symbols[23u],
	      "lut_row_serverAdapter_outData_enqData",
	      SYM_MODULE,
	      &INST_lut_row_serverAdapter_outData_enqData);
  init_symbol(&symbols[24u],
	      "lut_row_serverAdapter_outData_outData",
	      SYM_MODULE,
	      &INST_lut_row_serverAdapter_outData_outData);
  init_symbol(&symbols[25u],
	      "lut_row_serverAdapter_outDataCore",
	      SYM_MODULE,
	      &INST_lut_row_serverAdapter_outDataCore);
  init_symbol(&symbols[26u], "lut_row_serverAdapter_s1", SYM_MODULE, &INST_lut_row_serverAdapter_s1);
  init_symbol(&symbols[27u],
	      "lut_row_serverAdapter_s1_1",
	      SYM_MODULE,
	      &INST_lut_row_serverAdapter_s1_1);
  init_symbol(&symbols[28u],
	      "lut_row_serverAdapter_writeWithResp",
	      SYM_MODULE,
	      &INST_lut_row_serverAdapter_writeWithResp);
  init_symbol(&symbols[29u], "nz_num", SYM_MODULE, &INST_nz_num);
  init_symbol(&symbols[30u], "out", SYM_MODULE, &INST_out);
  init_symbol(&symbols[31u], "out_fifo", SYM_MODULE, &INST_out_fifo);
  init_symbol(&symbols[32u], "RL_complete", SYM_RULE);
  init_symbol(&symbols[33u], "RL_initiateBMVM", SYM_RULE);
  init_symbol(&symbols[34u], "RL_initiateRow", SYM_RULE);
  init_symbol(&symbols[35u], "RL_lut_nnz_serverAdapter_cnt_finalAdd", SYM_RULE);
  init_symbol(&symbols[36u], "RL_lut_nnz_serverAdapter_moveToOutFIFO", SYM_RULE);
  init_symbol(&symbols[37u], "RL_lut_nnz_serverAdapter_outData_deqOnly", SYM_RULE);
  init_symbol(&symbols[38u], "RL_lut_nnz_serverAdapter_outData_enqAndDeq", SYM_RULE);
  init_symbol(&symbols[39u], "RL_lut_nnz_serverAdapter_outData_enqOnly", SYM_RULE);
  init_symbol(&symbols[40u], "RL_lut_nnz_serverAdapter_outData_setFirstCore", SYM_RULE);
  init_symbol(&symbols[41u], "RL_lut_nnz_serverAdapter_outData_setFirstEnq", SYM_RULE);
  init_symbol(&symbols[42u], "RL_lut_nnz_serverAdapter_overRun", SYM_RULE);
  init_symbol(&symbols[43u], "RL_lut_nnz_serverAdapter_s1__dreg_update", SYM_RULE);
  init_symbol(&symbols[44u], "RL_lut_nnz_serverAdapter_stageReadResponseAlways", SYM_RULE);
  init_symbol(&symbols[45u], "RL_lut_row_serverAdapter_cnt_finalAdd", SYM_RULE);
  init_symbol(&symbols[46u], "RL_lut_row_serverAdapter_moveToOutFIFO", SYM_RULE);
  init_symbol(&symbols[47u], "RL_lut_row_serverAdapter_outData_deqOnly", SYM_RULE);
  init_symbol(&symbols[48u], "RL_lut_row_serverAdapter_outData_enqAndDeq", SYM_RULE);
  init_symbol(&symbols[49u], "RL_lut_row_serverAdapter_outData_enqOnly", SYM_RULE);
  init_symbol(&symbols[50u], "RL_lut_row_serverAdapter_outData_setFirstCore", SYM_RULE);
  init_symbol(&symbols[51u], "RL_lut_row_serverAdapter_outData_setFirstEnq", SYM_RULE);
  init_symbol(&symbols[52u], "RL_lut_row_serverAdapter_overRun", SYM_RULE);
  init_symbol(&symbols[53u], "RL_lut_row_serverAdapter_s1__dreg_update", SYM_RULE);
  init_symbol(&symbols[54u], "RL_lut_row_serverAdapter_stageReadResponseAlways", SYM_RULE);
  init_symbol(&symbols[55u], "RL_multiplyRow", SYM_RULE);
  init_symbol(&symbols[56u], "row_end", SYM_MODULE, &INST_row_end);
  init_symbol(&symbols[57u], "row_num", SYM_MODULE, &INST_row_num);
  init_symbol(&symbols[58u], "row_start", SYM_MODULE, &INST_row_start);
  init_symbol(&symbols[59u], "state", SYM_MODULE, &INST_state);
  init_symbol(&symbols[60u], "v__h4088", SYM_DEF, &DEF_v__h4088, 6u);
  init_symbol(&symbols[61u], "x__h4587", SYM_DEF, &DEF_x__h4587, 6u);
  init_symbol(&symbols[62u], "x__h5005", SYM_DEF, &DEF_x__h5005, 5u);
  init_symbol(&symbols[63u], "x__h5087", SYM_DEF, &DEF_x__h5087, 6u);
  init_symbol(&symbols[64u], "y__h4262", SYM_DEF, &DEF_y__h4262, 6u);
  init_symbol(&symbols[65u], "y__h4586", SYM_DEF, &DEF_y__h4586, 6u);
}


/* Rule actions */

void MOD_mkCsrBMVM::RL_lut_nnz_serverAdapter_outData_setFirstCore()
{
  tUInt8 DEF_x__h1037;
  DEF_x__h1037 = INST_lut_nnz_serverAdapter_outDataCore.METH_first();
  INST_lut_nnz_serverAdapter_outData_outData.METH_wset(DEF_x__h1037);
}

void MOD_mkCsrBMVM::RL_lut_nnz_serverAdapter_outData_setFirstEnq()
{
  DEF_x__h1126 = INST_lut_nnz_serverAdapter_outData_enqData.METH_wget();
  INST_lut_nnz_serverAdapter_outData_outData.METH_wset(DEF_x__h1126);
}

void MOD_mkCsrBMVM::RL_lut_nnz_serverAdapter_outData_enqOnly()
{
  DEF_x__h1126 = INST_lut_nnz_serverAdapter_outData_enqData.METH_wget();
  INST_lut_nnz_serverAdapter_outDataCore.METH_enq(DEF_x__h1126);
}

void MOD_mkCsrBMVM::RL_lut_nnz_serverAdapter_outData_deqOnly()
{
  INST_lut_nnz_serverAdapter_outDataCore.METH_deq();
}

void MOD_mkCsrBMVM::RL_lut_nnz_serverAdapter_outData_enqAndDeq()
{
  DEF_x__h1126 = INST_lut_nnz_serverAdapter_outData_enqData.METH_wget();
  INST_lut_nnz_serverAdapter_outDataCore.METH_enq(DEF_x__h1126);
  INST_lut_nnz_serverAdapter_outDataCore.METH_deq();
}

void MOD_mkCsrBMVM::RL_lut_nnz_serverAdapter_cnt_finalAdd()
{
  tUInt8 DEF_IF_lut_nnz_serverAdapter_cnt_3_whas__3_THEN_lu_ETC___d33;
  tUInt8 DEF_b__h1504;
  DEF_b__h1504 = INST_lut_nnz_serverAdapter_cnt_3.METH_wget();
  DEF_b__h1524 = INST_lut_nnz_serverAdapter_cnt.METH_read();
  DEF_lut_nnz_serverAdapter_cnt_3_whas____d23 = INST_lut_nnz_serverAdapter_cnt_3.METH_whas();
  DEF_lut_nnz_serverAdapter_cnt_2_whas____d21 = INST_lut_nnz_serverAdapter_cnt_2.METH_whas();
  DEF_lut_nnz_serverAdapter_cnt_1_whas____d20 = INST_lut_nnz_serverAdapter_cnt_1.METH_whas();
  DEF_IF_lut_nnz_serverAdapter_cnt_3_whas__3_THEN_lu_ETC___d33 = DEF_lut_nnz_serverAdapter_cnt_3_whas____d23 ? DEF_b__h1504 : (tUInt8)7u & (((tUInt8)7u & (DEF_b__h1524 + (DEF_lut_nnz_serverAdapter_cnt_1_whas____d20 ? INST_lut_nnz_serverAdapter_cnt_1.METH_wget() : (tUInt8)0u))) + (DEF_lut_nnz_serverAdapter_cnt_2_whas____d21 ? INST_lut_nnz_serverAdapter_cnt_2.METH_wget() : (tUInt8)0u));
  INST_lut_nnz_serverAdapter_cnt.METH_write(DEF_IF_lut_nnz_serverAdapter_cnt_3_whas__3_THEN_lu_ETC___d33);
}

void MOD_mkCsrBMVM::RL_lut_nnz_serverAdapter_s1__dreg_update()
{
  tUInt8 DEF_lut_nnz_serverAdapter_s1_1_whas__4_AND_0_OR_lu_ETC___d42;
  tUInt8 DEF_IF_lut_nnz_serverAdapter_s1_1_wget__5_BIT_1_6__ETC___d40;
  tUInt8 DEF_lut_nnz_serverAdapter_s1_1_wget__5_BIT_0___d39;
  tUInt8 DEF_lut_nnz_serverAdapter_s1_1_wget__5_BIT_1___d36;
  tUInt8 DEF_lut_nnz_serverAdapter_s1_1_whas____d34;
  tUInt8 DEF_lut_nnz_serverAdapter_s1_1_wget____d35;
  DEF_lut_nnz_serverAdapter_s1_1_wget____d35 = INST_lut_nnz_serverAdapter_s1_1.METH_wget();
  DEF_lut_nnz_serverAdapter_s1_1_whas____d34 = INST_lut_nnz_serverAdapter_s1_1.METH_whas();
  DEF_lut_nnz_serverAdapter_s1_1_wget__5_BIT_1___d36 = (tUInt8)(DEF_lut_nnz_serverAdapter_s1_1_wget____d35 >> 1u);
  DEF_lut_nnz_serverAdapter_s1_1_wget__5_BIT_0___d39 = (tUInt8)((tUInt8)1u & DEF_lut_nnz_serverAdapter_s1_1_wget____d35);
  DEF_IF_lut_nnz_serverAdapter_s1_1_wget__5_BIT_1_6__ETC___d40 = DEF_lut_nnz_serverAdapter_s1_1_wget__5_BIT_1___d36 ? DEF_lut_nnz_serverAdapter_s1_1_wget__5_BIT_0___d39 : DEF_lut_nnz_serverAdapter_s1_1_wget__5_BIT_0___d39;
  DEF_lut_nnz_serverAdapter_s1_1_whas__4_AND_0_OR_lu_ETC___d42 = (tUInt8)3u & (((DEF_lut_nnz_serverAdapter_s1_1_whas____d34 && DEF_lut_nnz_serverAdapter_s1_1_wget__5_BIT_1___d36) << 1u) | (DEF_lut_nnz_serverAdapter_s1_1_whas____d34 ? DEF_IF_lut_nnz_serverAdapter_s1_1_wget__5_BIT_1_6__ETC___d40 : DEF_IF_lut_nnz_serverAdapter_s1_1_wget__5_BIT_1_6__ETC___d40));
  INST_lut_nnz_serverAdapter_s1.METH_write(DEF_lut_nnz_serverAdapter_s1_1_whas__4_AND_0_OR_lu_ETC___d42);
}

void MOD_mkCsrBMVM::RL_lut_nnz_serverAdapter_stageReadResponseAlways()
{
  tUInt8 DEF_NOT_lut_nnz_serverAdapter_writeWithResp_wget___ETC___d48;
  tUInt8 DEF__1_CONCAT_NOT_lut_nnz_serverAdapter_writeWithRe_ETC___d49;
  tUInt8 DEF_ab_BIT_0___h2027;
  tUInt8 DEF_ab_BIT_1___h2021;
  tUInt8 DEF_ab__h2013;
  DEF_ab__h2013 = INST_lut_nnz_serverAdapter_writeWithResp.METH_wget();
  DEF_ab_BIT_1___h2021 = (tUInt8)(DEF_ab__h2013 >> 1u);
  DEF_ab_BIT_0___h2027 = (tUInt8)((tUInt8)1u & DEF_ab__h2013);
  DEF_NOT_lut_nnz_serverAdapter_writeWithResp_wget___ETC___d48 = !DEF_ab_BIT_1___h2021 || DEF_ab_BIT_0___h2027;
  DEF__1_CONCAT_NOT_lut_nnz_serverAdapter_writeWithRe_ETC___d49 = (tUInt8)3u & (((tUInt8)1u << 1u) | DEF_NOT_lut_nnz_serverAdapter_writeWithResp_wget___ETC___d48);
  INST_lut_nnz_serverAdapter_s1_1.METH_wset(DEF__1_CONCAT_NOT_lut_nnz_serverAdapter_writeWithRe_ETC___d49);
  if (DEF_NOT_lut_nnz_serverAdapter_writeWithResp_wget___ETC___d48)
    INST_lut_nnz_serverAdapter_cnt_1.METH_wset((tUInt8)1u);
}

void MOD_mkCsrBMVM::RL_lut_nnz_serverAdapter_moveToOutFIFO()
{
  tUInt8 DEF_v__h2130;
  DEF_v__h2130 = INST_lut_nnz_memory.METH_read();
  DEF_lut_nnz_serverAdapter_s1___d50 = INST_lut_nnz_serverAdapter_s1.METH_read();
  DEF_lut_nnz_serverAdapter_s1_0_BIT_0___d51 = (tUInt8)((tUInt8)1u & DEF_lut_nnz_serverAdapter_s1___d50);
  if (DEF_lut_nnz_serverAdapter_s1_0_BIT_0___d51)
    INST_lut_nnz_serverAdapter_outData_enqData.METH_wset(DEF_v__h2130);
}

void MOD_mkCsrBMVM::RL_lut_nnz_serverAdapter_overRun()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s", &__str_literal_3);
}

void MOD_mkCsrBMVM::RL_lut_row_serverAdapter_outData_setFirstCore()
{
  tUInt8 DEF_x__h2597;
  DEF_x__h2597 = INST_lut_row_serverAdapter_outDataCore.METH_first();
  INST_lut_row_serverAdapter_outData_outData.METH_wset(DEF_x__h2597);
}

void MOD_mkCsrBMVM::RL_lut_row_serverAdapter_outData_setFirstEnq()
{
  DEF_x__h2686 = INST_lut_row_serverAdapter_outData_enqData.METH_wget();
  INST_lut_row_serverAdapter_outData_outData.METH_wset(DEF_x__h2686);
}

void MOD_mkCsrBMVM::RL_lut_row_serverAdapter_outData_enqOnly()
{
  DEF_x__h2686 = INST_lut_row_serverAdapter_outData_enqData.METH_wget();
  INST_lut_row_serverAdapter_outDataCore.METH_enq(DEF_x__h2686);
}

void MOD_mkCsrBMVM::RL_lut_row_serverAdapter_outData_deqOnly()
{
  INST_lut_row_serverAdapter_outDataCore.METH_deq();
}

void MOD_mkCsrBMVM::RL_lut_row_serverAdapter_outData_enqAndDeq()
{
  DEF_x__h2686 = INST_lut_row_serverAdapter_outData_enqData.METH_wget();
  INST_lut_row_serverAdapter_outDataCore.METH_enq(DEF_x__h2686);
  INST_lut_row_serverAdapter_outDataCore.METH_deq();
}

void MOD_mkCsrBMVM::RL_lut_row_serverAdapter_cnt_finalAdd()
{
  tUInt8 DEF_IF_lut_row_serverAdapter_cnt_3_whas__2_THEN_lu_ETC___d92;
  tUInt8 DEF_b__h3064;
  DEF_b__h3064 = INST_lut_row_serverAdapter_cnt_3.METH_wget();
  DEF_b__h3084 = INST_lut_row_serverAdapter_cnt.METH_read();
  DEF_lut_row_serverAdapter_cnt_3_whas____d82 = INST_lut_row_serverAdapter_cnt_3.METH_whas();
  DEF_lut_row_serverAdapter_cnt_2_whas____d80 = INST_lut_row_serverAdapter_cnt_2.METH_whas();
  DEF_lut_row_serverAdapter_cnt_1_whas____d79 = INST_lut_row_serverAdapter_cnt_1.METH_whas();
  DEF_IF_lut_row_serverAdapter_cnt_3_whas__2_THEN_lu_ETC___d92 = DEF_lut_row_serverAdapter_cnt_3_whas____d82 ? DEF_b__h3064 : (tUInt8)7u & (((tUInt8)7u & (DEF_b__h3084 + (DEF_lut_row_serverAdapter_cnt_1_whas____d79 ? INST_lut_row_serverAdapter_cnt_1.METH_wget() : (tUInt8)0u))) + (DEF_lut_row_serverAdapter_cnt_2_whas____d80 ? INST_lut_row_serverAdapter_cnt_2.METH_wget() : (tUInt8)0u));
  INST_lut_row_serverAdapter_cnt.METH_write(DEF_IF_lut_row_serverAdapter_cnt_3_whas__2_THEN_lu_ETC___d92);
}

void MOD_mkCsrBMVM::RL_lut_row_serverAdapter_s1__dreg_update()
{
  tUInt8 DEF_lut_row_serverAdapter_s1_1_whas__3_AND_0_OR_lu_ETC___d101;
  tUInt8 DEF_IF_lut_row_serverAdapter_s1_1_wget__4_BIT_1_5__ETC___d99;
  tUInt8 DEF_lut_row_serverAdapter_s1_1_wget__4_BIT_0___d98;
  tUInt8 DEF_lut_row_serverAdapter_s1_1_wget__4_BIT_1___d95;
  tUInt8 DEF_lut_row_serverAdapter_s1_1_whas____d93;
  tUInt8 DEF_lut_row_serverAdapter_s1_1_wget____d94;
  DEF_lut_row_serverAdapter_s1_1_wget____d94 = INST_lut_row_serverAdapter_s1_1.METH_wget();
  DEF_lut_row_serverAdapter_s1_1_whas____d93 = INST_lut_row_serverAdapter_s1_1.METH_whas();
  DEF_lut_row_serverAdapter_s1_1_wget__4_BIT_1___d95 = (tUInt8)(DEF_lut_row_serverAdapter_s1_1_wget____d94 >> 1u);
  DEF_lut_row_serverAdapter_s1_1_wget__4_BIT_0___d98 = (tUInt8)((tUInt8)1u & DEF_lut_row_serverAdapter_s1_1_wget____d94);
  DEF_IF_lut_row_serverAdapter_s1_1_wget__4_BIT_1_5__ETC___d99 = DEF_lut_row_serverAdapter_s1_1_wget__4_BIT_1___d95 ? DEF_lut_row_serverAdapter_s1_1_wget__4_BIT_0___d98 : DEF_lut_row_serverAdapter_s1_1_wget__4_BIT_0___d98;
  DEF_lut_row_serverAdapter_s1_1_whas__3_AND_0_OR_lu_ETC___d101 = (tUInt8)3u & (((DEF_lut_row_serverAdapter_s1_1_whas____d93 && DEF_lut_row_serverAdapter_s1_1_wget__4_BIT_1___d95) << 1u) | (DEF_lut_row_serverAdapter_s1_1_whas____d93 ? DEF_IF_lut_row_serverAdapter_s1_1_wget__4_BIT_1_5__ETC___d99 : DEF_IF_lut_row_serverAdapter_s1_1_wget__4_BIT_1_5__ETC___d99));
  INST_lut_row_serverAdapter_s1.METH_write(DEF_lut_row_serverAdapter_s1_1_whas__3_AND_0_OR_lu_ETC___d101);
}

void MOD_mkCsrBMVM::RL_lut_row_serverAdapter_stageReadResponseAlways()
{
  tUInt8 DEF_NOT_lut_row_serverAdapter_writeWithResp_wget___ETC___d107;
  tUInt8 DEF__1_CONCAT_NOT_lut_row_serverAdapter_writeWithRe_ETC___d108;
  tUInt8 DEF_ab_BIT_0___h3587;
  tUInt8 DEF_ab_BIT_1___h3581;
  tUInt8 DEF_ab__h3573;
  DEF_ab__h3573 = INST_lut_row_serverAdapter_writeWithResp.METH_wget();
  DEF_ab_BIT_1___h3581 = (tUInt8)(DEF_ab__h3573 >> 1u);
  DEF_ab_BIT_0___h3587 = (tUInt8)((tUInt8)1u & DEF_ab__h3573);
  DEF_NOT_lut_row_serverAdapter_writeWithResp_wget___ETC___d107 = !DEF_ab_BIT_1___h3581 || DEF_ab_BIT_0___h3587;
  DEF__1_CONCAT_NOT_lut_row_serverAdapter_writeWithRe_ETC___d108 = (tUInt8)3u & (((tUInt8)1u << 1u) | DEF_NOT_lut_row_serverAdapter_writeWithResp_wget___ETC___d107);
  INST_lut_row_serverAdapter_s1_1.METH_wset(DEF__1_CONCAT_NOT_lut_row_serverAdapter_writeWithRe_ETC___d108);
  if (DEF_NOT_lut_row_serverAdapter_writeWithResp_wget___ETC___d107)
    INST_lut_row_serverAdapter_cnt_1.METH_wset((tUInt8)1u);
}

void MOD_mkCsrBMVM::RL_lut_row_serverAdapter_moveToOutFIFO()
{
  tUInt8 DEF_v__h3690;
  DEF_v__h3690 = INST_lut_row_memory.METH_read();
  DEF_lut_row_serverAdapter_s1___d109 = INST_lut_row_serverAdapter_s1.METH_read();
  DEF_lut_row_serverAdapter_s1_09_BIT_0___d110 = (tUInt8)((tUInt8)1u & DEF_lut_row_serverAdapter_s1___d109);
  if (DEF_lut_row_serverAdapter_s1_09_BIT_0___d110)
    INST_lut_row_serverAdapter_outData_enqData.METH_wset(DEF_v__h3690);
}

void MOD_mkCsrBMVM::RL_lut_row_serverAdapter_overRun()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s", &__str_literal_3);
}

void MOD_mkCsrBMVM::RL_initiateBMVM()
{
  tUInt32 DEF_x__h3809;
  DEF_x__h3809 = INST_in_fifo.METH_first();
  DEF_x__h5005 = INST_row_num.METH_read();
  DEF_x__h4819 = (tUInt8)31u & (DEF_x__h5005 + (tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s", &__str_literal_4);
  INST_in_fifo.METH_deq();
  INST_in.METH_write(DEF_x__h3809);
  INST_lut_row_memory.METH_put((tUInt8)0u, DEF_x__h5005, (tUInt8)42u);
  INST_lut_row_serverAdapter_writeWithResp.METH_wset((tUInt8)0u);
  if (!(PORT_RST_N == (tUInt8)0u))
  {
    dollar_display(sim_hdl, this, "s", &__str_literal_5);
    dollar_display(sim_hdl, this, "s,s", &__str_literal_6, &__str_literal_7);
  }
  INST_state.METH_write((tUInt8)1u);
  INST_row_num.METH_write(DEF_x__h4819);
}

void MOD_mkCsrBMVM::RL_initiateRow()
{
  tUInt8 DEF_NOT_lut_row_serverAdapter_outData_outData_wget_ETC___d140;
  tUInt8 DEF_IF_lut_row_serverAdapter_outData_outData_wget__ETC___d139;
  DEF_v__h4088 = INST_lut_row_serverAdapter_outData_outData.METH_wget();
  DEF_y__h4262 = INST_row_start.METH_read();
  DEF_x__h5087 = INST_nz_num.METH_read();
  DEF_x__h5005 = INST_row_num.METH_read();
  DEF_lut_row_serverAdapter_outData_outData_wget__30_ETC___d132 = DEF_v__h4088 == DEF_y__h4262;
  DEF_IF_lut_row_serverAdapter_outData_outData_wget__ETC___d139 = DEF_lut_row_serverAdapter_outData_outData_wget__30_ETC___d132 ? (tUInt8)1u : (tUInt8)2u;
  DEF_NOT_lut_row_serverAdapter_outData_outData_wget_ETC___d140 = !DEF_lut_row_serverAdapter_outData_outData_wget__30_ETC___d132;
  DEF_x__h5077 = (tUInt8)63u & (DEF_x__h5087 + (tUInt8)1u);
  DEF_x__h4819 = (tUInt8)31u & (DEF_x__h5005 + (tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s", &__str_literal_8);
  INST_lut_row_serverAdapter_cnt_2.METH_wset((tUInt8)7u);
  INST_lut_row_serverAdapter_outData_deqCalled.METH_wset();
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,6", &__str_literal_9, DEF_v__h4088);
  INST_row_start.METH_write(DEF_v__h4088);
  INST_row_end.METH_write(DEF_v__h4088);
  INST_state.METH_write(DEF_IF_lut_row_serverAdapter_outData_outData_wget__ETC___d139);
  if (DEF_lut_row_serverAdapter_outData_outData_wget__30_ETC___d132)
    INST_lut_row_memory.METH_put((tUInt8)0u, DEF_x__h5005, (tUInt8)42u);
  if (DEF_lut_row_serverAdapter_outData_outData_wget__30_ETC___d132)
    INST_row_num.METH_write(DEF_x__h4819);
  if (DEF_lut_row_serverAdapter_outData_outData_wget__30_ETC___d132)
    INST_lut_row_serverAdapter_writeWithResp.METH_wset((tUInt8)0u);
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_lut_row_serverAdapter_outData_outData_wget__30_ETC___d132)
      dollar_display(sim_hdl, this, "s", &__str_literal_5);
  if (DEF_NOT_lut_row_serverAdapter_outData_outData_wget_ETC___d140)
    INST_lut_nnz_memory.METH_put((tUInt8)0u, DEF_x__h5087, (tUInt8)10u);
  if (DEF_NOT_lut_row_serverAdapter_outData_outData_wget_ETC___d140)
    INST_lut_nnz_serverAdapter_writeWithResp.METH_wset((tUInt8)0u);
  if (DEF_NOT_lut_row_serverAdapter_outData_outData_wget_ETC___d140)
    INST_nz_num.METH_write(DEF_x__h5077);
}

void MOD_mkCsrBMVM::RL_multiplyRow()
{
  tUInt32 DEF_x__h4987;
  tUInt32 DEF_y__h5059;
  tUInt8 DEF_nz_num_41_EQ_row_end_43_PLUS_1_44_45_AND_NOT_r_ETC___d160;
  tUInt8 DEF_NOT_nz_num_41_EQ_row_end_43_PLUS_1_44_45___d161;
  tUInt8 DEF_NOT_nz_num_41_EQ_row_end_43_PLUS_1_44_45_61_AN_ETC___d163;
  tUInt8 DEF_IF_nz_num_41_EQ_row_end_43_PLUS_1_44_45_THEN_I_ETC___d158;
  tUInt32 DEF_x__h4973;
  tUInt8 DEF_i__h5000;
  tUInt8 DEF_v__h4631;
  tUInt32 DEF_bs__h5013;
  DEF_x__h5146 = INST_out.METH_read();
  DEF_bs__h5013 = INST_in.METH_read();
  DEF_x__h4587 = INST_row_end.METH_read();
  DEF_x__h5087 = INST_nz_num.METH_read();
  DEF_v__h4631 = INST_lut_nnz_serverAdapter_outData_outData.METH_wget();
  DEF_x__h5005 = INST_row_num.METH_read();
  DEF_i__h5000 = (tUInt8)31u & (DEF_x__h5005 - (tUInt8)1u);
  DEF_row_num_26_EQ_0___d146 = DEF_x__h5005 == (tUInt8)0u;
  DEF_y__h4586 = (tUInt8)63u & (DEF_x__h4587 + (tUInt8)1u);
  DEF_nz_num_41_EQ_row_end_43_PLUS_1_44___d145 = DEF_x__h5087 == DEF_y__h4586;
  DEF_IF_nz_num_41_EQ_row_end_43_PLUS_1_44_45_THEN_I_ETC___d158 = DEF_nz_num_41_EQ_row_end_43_PLUS_1_44___d145 ? (DEF_row_num_26_EQ_0___d146 ? (tUInt8)3u : (tUInt8)1u) : (tUInt8)2u;
  DEF_nz_num_41_ULT_row_end_43___d150 = DEF_x__h5087 < DEF_x__h4587;
  DEF_NOT_nz_num_41_EQ_row_end_43_PLUS_1_44_45___d161 = !DEF_nz_num_41_EQ_row_end_43_PLUS_1_44___d145;
  DEF_NOT_nz_num_41_EQ_row_end_43_PLUS_1_44_45_61_AN_ETC___d163 = DEF_NOT_nz_num_41_EQ_row_end_43_PLUS_1_44_45___d161 && !DEF_nz_num_41_ULT_row_end_43___d150;
  DEF_nz_num_41_EQ_row_end_43_PLUS_1_44_45_AND_NOT_r_ETC___d160 = DEF_nz_num_41_EQ_row_end_43_PLUS_1_44___d145 && !DEF_row_num_26_EQ_0___d146;
  DEF_x__h4987 = primShiftL32(32u, 32u, 1u, 5u, (tUInt8)(DEF_i__h5000));
  DEF_y__h5059 = ~DEF_x__h4987;
  DEF_x__h4973 = primExtract8(1u,
			      32u,
			      (tUInt32)(DEF_x__h5146),
			      5u,
			      (tUInt8)(DEF_i__h5000),
			      5u,
			      (tUInt8)(DEF_i__h5000)) ^ primExtract8(1u,
								     32u,
								     (tUInt32)(DEF_bs__h5013),
								     5u,
								     (tUInt8)(DEF_v__h4631),
								     5u,
								     (tUInt8)(DEF_v__h4631)) ? DEF_x__h5146 | DEF_x__h4987 : DEF_x__h5146 & DEF_y__h5059;
  DEF_x__h5077 = (tUInt8)63u & (DEF_x__h5087 + (tUInt8)1u);
  DEF_x__h4819 = (tUInt8)31u & (DEF_x__h5005 + (tUInt8)1u);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s", &__str_literal_10);
  INST_state.METH_write(DEF_IF_nz_num_41_EQ_row_end_43_PLUS_1_44_45_THEN_I_ETC___d158);
  if (DEF_nz_num_41_EQ_row_end_43_PLUS_1_44_45_AND_NOT_r_ETC___d160)
    INST_lut_row_memory.METH_put((tUInt8)0u, DEF_x__h5005, (tUInt8)42u);
  if (DEF_nz_num_41_EQ_row_end_43_PLUS_1_44_45_AND_NOT_r_ETC___d160)
    INST_lut_row_serverAdapter_writeWithResp.METH_wset((tUInt8)0u);
  if (DEF_nz_num_41_EQ_row_end_43_PLUS_1_44_45_AND_NOT_r_ETC___d160)
    INST_row_num.METH_write(DEF_x__h4819);
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_nz_num_41_EQ_row_end_43_PLUS_1_44_45_AND_NOT_r_ETC___d160)
      dollar_display(sim_hdl, this, "s", &__str_literal_5);
  if (DEF_NOT_nz_num_41_EQ_row_end_43_PLUS_1_44_45___d161)
    INST_lut_nnz_serverAdapter_outData_deqCalled.METH_wset();
  if (DEF_NOT_nz_num_41_EQ_row_end_43_PLUS_1_44_45___d161)
    INST_lut_nnz_serverAdapter_cnt_2.METH_wset((tUInt8)7u);
  if (DEF_NOT_nz_num_41_EQ_row_end_43_PLUS_1_44_45_61_AN_ETC___d163)
    INST_lut_nnz_memory.METH_put((tUInt8)0u, DEF_x__h5087, (tUInt8)10u);
  if (DEF_NOT_nz_num_41_EQ_row_end_43_PLUS_1_44_45_61_AN_ETC___d163)
    INST_lut_nnz_serverAdapter_writeWithResp.METH_wset((tUInt8)0u);
  if (DEF_NOT_nz_num_41_EQ_row_end_43_PLUS_1_44_45___d161)
    INST_out.METH_write(DEF_x__h4973);
  if (DEF_NOT_nz_num_41_EQ_row_end_43_PLUS_1_44_45___d161)
    INST_nz_num.METH_write(DEF_x__h5077);
}

void MOD_mkCsrBMVM::RL_complete()
{
  DEF_x__h5146 = INST_out.METH_read();
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s", &__str_literal_11);
  INST_out_fifo.METH_enq(DEF_x__h5146);
  INST_state.METH_write((tUInt8)0u);
  INST_nz_num.METH_write((tUInt8)0u);
  INST_row_num.METH_write((tUInt8)0u);
}


/* Methods */

tUInt32 MOD_mkCsrBMVM::METH_get()
{
  tUInt32 DEF_get__avValue1;
  tUInt32 PORT_get;
  DEF_get__avValue1 = INST_out_fifo.METH_first();
  PORT_get = DEF_get__avValue1;
  INST_out_fifo.METH_deq();
  return PORT_get;
}

tUInt8 MOD_mkCsrBMVM::METH_RDY_get()
{
  tUInt8 PORT_RDY_get;
  tUInt8 DEF_CAN_FIRE_get;
  DEF_CAN_FIRE_get = INST_out_fifo.METH_i_notEmpty();
  PORT_RDY_get = DEF_CAN_FIRE_get;
  return PORT_RDY_get;
}

void MOD_mkCsrBMVM::METH_put(tUInt32 ARG_put_x)
{
  INST_in_fifo.METH_enq(ARG_put_x);
}

tUInt8 MOD_mkCsrBMVM::METH_RDY_put()
{
  tUInt8 PORT_RDY_put;
  tUInt8 DEF_CAN_FIRE_put;
  DEF_CAN_FIRE_put = INST_in_fifo.METH_i_notFull();
  PORT_RDY_put = DEF_CAN_FIRE_put;
  return PORT_RDY_put;
}


/* Reset routines */

void MOD_mkCsrBMVM::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_state.reset_RST(ARG_rst_in);
  INST_row_start.reset_RST(ARG_rst_in);
  INST_row_num.reset_RST(ARG_rst_in);
  INST_row_end.reset_RST(ARG_rst_in);
  INST_out_fifo.reset_RST(ARG_rst_in);
  INST_out.reset_RST(ARG_rst_in);
  INST_nz_num.reset_RST(ARG_rst_in);
  INST_lut_row_serverAdapter_s1.reset_RST(ARG_rst_in);
  INST_lut_row_serverAdapter_outDataCore.reset_RST(ARG_rst_in);
  INST_lut_row_serverAdapter_cnt.reset_RST(ARG_rst_in);
  INST_lut_nnz_serverAdapter_s1.reset_RST(ARG_rst_in);
  INST_lut_nnz_serverAdapter_outDataCore.reset_RST(ARG_rst_in);
  INST_lut_nnz_serverAdapter_cnt.reset_RST(ARG_rst_in);
  INST_in_fifo.reset_RST(ARG_rst_in);
  INST_in.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkCsrBMVM::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkCsrBMVM::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_in.dump_state(indent + 2u);
  INST_in_fifo.dump_state(indent + 2u);
  INST_lut_nnz_memory.dump_state(indent + 2u);
  INST_lut_nnz_serverAdapter_cnt.dump_state(indent + 2u);
  INST_lut_nnz_serverAdapter_cnt_1.dump_state(indent + 2u);
  INST_lut_nnz_serverAdapter_cnt_2.dump_state(indent + 2u);
  INST_lut_nnz_serverAdapter_cnt_3.dump_state(indent + 2u);
  INST_lut_nnz_serverAdapter_outDataCore.dump_state(indent + 2u);
  INST_lut_nnz_serverAdapter_outData_deqCalled.dump_state(indent + 2u);
  INST_lut_nnz_serverAdapter_outData_enqData.dump_state(indent + 2u);
  INST_lut_nnz_serverAdapter_outData_outData.dump_state(indent + 2u);
  INST_lut_nnz_serverAdapter_s1.dump_state(indent + 2u);
  INST_lut_nnz_serverAdapter_s1_1.dump_state(indent + 2u);
  INST_lut_nnz_serverAdapter_writeWithResp.dump_state(indent + 2u);
  INST_lut_row_memory.dump_state(indent + 2u);
  INST_lut_row_serverAdapter_cnt.dump_state(indent + 2u);
  INST_lut_row_serverAdapter_cnt_1.dump_state(indent + 2u);
  INST_lut_row_serverAdapter_cnt_2.dump_state(indent + 2u);
  INST_lut_row_serverAdapter_cnt_3.dump_state(indent + 2u);
  INST_lut_row_serverAdapter_outDataCore.dump_state(indent + 2u);
  INST_lut_row_serverAdapter_outData_deqCalled.dump_state(indent + 2u);
  INST_lut_row_serverAdapter_outData_enqData.dump_state(indent + 2u);
  INST_lut_row_serverAdapter_outData_outData.dump_state(indent + 2u);
  INST_lut_row_serverAdapter_s1.dump_state(indent + 2u);
  INST_lut_row_serverAdapter_s1_1.dump_state(indent + 2u);
  INST_lut_row_serverAdapter_writeWithResp.dump_state(indent + 2u);
  INST_nz_num.dump_state(indent + 2u);
  INST_out.dump_state(indent + 2u);
  INST_out_fifo.dump_state(indent + 2u);
  INST_row_end.dump_state(indent + 2u);
  INST_row_num.dump_state(indent + 2u);
  INST_row_start.dump_state(indent + 2u);
  INST_state.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkCsrBMVM::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 61u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h1524", 3u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h3084", 3u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "lut_nnz_serverAdapter_cnt_1_whas____d20", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "lut_nnz_serverAdapter_cnt_2_whas____d21", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "lut_nnz_serverAdapter_cnt_3_whas____d23", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "lut_nnz_serverAdapter_s1_0_BIT_0___d51", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "lut_nnz_serverAdapter_s1___d50", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "lut_row_serverAdapter_cnt_1_whas____d79", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "lut_row_serverAdapter_cnt_2_whas____d80", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "lut_row_serverAdapter_cnt_3_whas____d82", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "lut_row_serverAdapter_outData_outData_wget__30_ETC___d132", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "lut_row_serverAdapter_s1_09_BIT_0___d110", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "lut_row_serverAdapter_s1___d109", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "nz_num_41_EQ_row_end_43_PLUS_1_44___d145", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "nz_num_41_ULT_row_end_43___d150", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "row_num_26_EQ_0___d146", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "v__h4088", 6u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h1126", 5u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h2686", 6u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h4587", 6u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h4819", 5u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h5005", 5u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h5077", 6u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h5087", 6u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h5146", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "y__h4262", 6u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "y__h4586", 6u);
  num = INST_in.dump_VCD_defs(num);
  num = INST_in_fifo.dump_VCD_defs(num);
  num = INST_lut_nnz_memory.dump_VCD_defs(num);
  num = INST_lut_nnz_serverAdapter_cnt.dump_VCD_defs(num);
  num = INST_lut_nnz_serverAdapter_cnt_1.dump_VCD_defs(num);
  num = INST_lut_nnz_serverAdapter_cnt_2.dump_VCD_defs(num);
  num = INST_lut_nnz_serverAdapter_cnt_3.dump_VCD_defs(num);
  num = INST_lut_nnz_serverAdapter_outDataCore.dump_VCD_defs(num);
  num = INST_lut_nnz_serverAdapter_outData_deqCalled.dump_VCD_defs(num);
  num = INST_lut_nnz_serverAdapter_outData_enqData.dump_VCD_defs(num);
  num = INST_lut_nnz_serverAdapter_outData_outData.dump_VCD_defs(num);
  num = INST_lut_nnz_serverAdapter_s1.dump_VCD_defs(num);
  num = INST_lut_nnz_serverAdapter_s1_1.dump_VCD_defs(num);
  num = INST_lut_nnz_serverAdapter_writeWithResp.dump_VCD_defs(num);
  num = INST_lut_row_memory.dump_VCD_defs(num);
  num = INST_lut_row_serverAdapter_cnt.dump_VCD_defs(num);
  num = INST_lut_row_serverAdapter_cnt_1.dump_VCD_defs(num);
  num = INST_lut_row_serverAdapter_cnt_2.dump_VCD_defs(num);
  num = INST_lut_row_serverAdapter_cnt_3.dump_VCD_defs(num);
  num = INST_lut_row_serverAdapter_outDataCore.dump_VCD_defs(num);
  num = INST_lut_row_serverAdapter_outData_deqCalled.dump_VCD_defs(num);
  num = INST_lut_row_serverAdapter_outData_enqData.dump_VCD_defs(num);
  num = INST_lut_row_serverAdapter_outData_outData.dump_VCD_defs(num);
  num = INST_lut_row_serverAdapter_s1.dump_VCD_defs(num);
  num = INST_lut_row_serverAdapter_s1_1.dump_VCD_defs(num);
  num = INST_lut_row_serverAdapter_writeWithResp.dump_VCD_defs(num);
  num = INST_nz_num.dump_VCD_defs(num);
  num = INST_out.dump_VCD_defs(num);
  num = INST_out_fifo.dump_VCD_defs(num);
  num = INST_row_end.dump_VCD_defs(num);
  num = INST_row_num.dump_VCD_defs(num);
  num = INST_row_start.dump_VCD_defs(num);
  num = INST_state.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkCsrBMVM::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkCsrBMVM &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkCsrBMVM::vcd_defs(tVCDDumpType dt, MOD_mkCsrBMVM &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 3u);
    vcd_write_x(sim_hdl, num++, 3u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 6u);
    vcd_write_x(sim_hdl, num++, 5u);
    vcd_write_x(sim_hdl, num++, 6u);
    vcd_write_x(sim_hdl, num++, 6u);
    vcd_write_x(sim_hdl, num++, 5u);
    vcd_write_x(sim_hdl, num++, 5u);
    vcd_write_x(sim_hdl, num++, 6u);
    vcd_write_x(sim_hdl, num++, 6u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 6u);
    vcd_write_x(sim_hdl, num++, 6u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_b__h1524) != DEF_b__h1524)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h1524, 3u);
	backing.DEF_b__h1524 = DEF_b__h1524;
      }
      ++num;
      if ((backing.DEF_b__h3084) != DEF_b__h3084)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h3084, 3u);
	backing.DEF_b__h3084 = DEF_b__h3084;
      }
      ++num;
      if ((backing.DEF_lut_nnz_serverAdapter_cnt_1_whas____d20) != DEF_lut_nnz_serverAdapter_cnt_1_whas____d20)
      {
	vcd_write_val(sim_hdl, num, DEF_lut_nnz_serverAdapter_cnt_1_whas____d20, 1u);
	backing.DEF_lut_nnz_serverAdapter_cnt_1_whas____d20 = DEF_lut_nnz_serverAdapter_cnt_1_whas____d20;
      }
      ++num;
      if ((backing.DEF_lut_nnz_serverAdapter_cnt_2_whas____d21) != DEF_lut_nnz_serverAdapter_cnt_2_whas____d21)
      {
	vcd_write_val(sim_hdl, num, DEF_lut_nnz_serverAdapter_cnt_2_whas____d21, 1u);
	backing.DEF_lut_nnz_serverAdapter_cnt_2_whas____d21 = DEF_lut_nnz_serverAdapter_cnt_2_whas____d21;
      }
      ++num;
      if ((backing.DEF_lut_nnz_serverAdapter_cnt_3_whas____d23) != DEF_lut_nnz_serverAdapter_cnt_3_whas____d23)
      {
	vcd_write_val(sim_hdl, num, DEF_lut_nnz_serverAdapter_cnt_3_whas____d23, 1u);
	backing.DEF_lut_nnz_serverAdapter_cnt_3_whas____d23 = DEF_lut_nnz_serverAdapter_cnt_3_whas____d23;
      }
      ++num;
      if ((backing.DEF_lut_nnz_serverAdapter_s1_0_BIT_0___d51) != DEF_lut_nnz_serverAdapter_s1_0_BIT_0___d51)
      {
	vcd_write_val(sim_hdl, num, DEF_lut_nnz_serverAdapter_s1_0_BIT_0___d51, 1u);
	backing.DEF_lut_nnz_serverAdapter_s1_0_BIT_0___d51 = DEF_lut_nnz_serverAdapter_s1_0_BIT_0___d51;
      }
      ++num;
      if ((backing.DEF_lut_nnz_serverAdapter_s1___d50) != DEF_lut_nnz_serverAdapter_s1___d50)
      {
	vcd_write_val(sim_hdl, num, DEF_lut_nnz_serverAdapter_s1___d50, 2u);
	backing.DEF_lut_nnz_serverAdapter_s1___d50 = DEF_lut_nnz_serverAdapter_s1___d50;
      }
      ++num;
      if ((backing.DEF_lut_row_serverAdapter_cnt_1_whas____d79) != DEF_lut_row_serverAdapter_cnt_1_whas____d79)
      {
	vcd_write_val(sim_hdl, num, DEF_lut_row_serverAdapter_cnt_1_whas____d79, 1u);
	backing.DEF_lut_row_serverAdapter_cnt_1_whas____d79 = DEF_lut_row_serverAdapter_cnt_1_whas____d79;
      }
      ++num;
      if ((backing.DEF_lut_row_serverAdapter_cnt_2_whas____d80) != DEF_lut_row_serverAdapter_cnt_2_whas____d80)
      {
	vcd_write_val(sim_hdl, num, DEF_lut_row_serverAdapter_cnt_2_whas____d80, 1u);
	backing.DEF_lut_row_serverAdapter_cnt_2_whas____d80 = DEF_lut_row_serverAdapter_cnt_2_whas____d80;
      }
      ++num;
      if ((backing.DEF_lut_row_serverAdapter_cnt_3_whas____d82) != DEF_lut_row_serverAdapter_cnt_3_whas____d82)
      {
	vcd_write_val(sim_hdl, num, DEF_lut_row_serverAdapter_cnt_3_whas____d82, 1u);
	backing.DEF_lut_row_serverAdapter_cnt_3_whas____d82 = DEF_lut_row_serverAdapter_cnt_3_whas____d82;
      }
      ++num;
      if ((backing.DEF_lut_row_serverAdapter_outData_outData_wget__30_ETC___d132) != DEF_lut_row_serverAdapter_outData_outData_wget__30_ETC___d132)
      {
	vcd_write_val(sim_hdl, num, DEF_lut_row_serverAdapter_outData_outData_wget__30_ETC___d132, 1u);
	backing.DEF_lut_row_serverAdapter_outData_outData_wget__30_ETC___d132 = DEF_lut_row_serverAdapter_outData_outData_wget__30_ETC___d132;
      }
      ++num;
      if ((backing.DEF_lut_row_serverAdapter_s1_09_BIT_0___d110) != DEF_lut_row_serverAdapter_s1_09_BIT_0___d110)
      {
	vcd_write_val(sim_hdl, num, DEF_lut_row_serverAdapter_s1_09_BIT_0___d110, 1u);
	backing.DEF_lut_row_serverAdapter_s1_09_BIT_0___d110 = DEF_lut_row_serverAdapter_s1_09_BIT_0___d110;
      }
      ++num;
      if ((backing.DEF_lut_row_serverAdapter_s1___d109) != DEF_lut_row_serverAdapter_s1___d109)
      {
	vcd_write_val(sim_hdl, num, DEF_lut_row_serverAdapter_s1___d109, 2u);
	backing.DEF_lut_row_serverAdapter_s1___d109 = DEF_lut_row_serverAdapter_s1___d109;
      }
      ++num;
      if ((backing.DEF_nz_num_41_EQ_row_end_43_PLUS_1_44___d145) != DEF_nz_num_41_EQ_row_end_43_PLUS_1_44___d145)
      {
	vcd_write_val(sim_hdl, num, DEF_nz_num_41_EQ_row_end_43_PLUS_1_44___d145, 1u);
	backing.DEF_nz_num_41_EQ_row_end_43_PLUS_1_44___d145 = DEF_nz_num_41_EQ_row_end_43_PLUS_1_44___d145;
      }
      ++num;
      if ((backing.DEF_nz_num_41_ULT_row_end_43___d150) != DEF_nz_num_41_ULT_row_end_43___d150)
      {
	vcd_write_val(sim_hdl, num, DEF_nz_num_41_ULT_row_end_43___d150, 1u);
	backing.DEF_nz_num_41_ULT_row_end_43___d150 = DEF_nz_num_41_ULT_row_end_43___d150;
      }
      ++num;
      if ((backing.DEF_row_num_26_EQ_0___d146) != DEF_row_num_26_EQ_0___d146)
      {
	vcd_write_val(sim_hdl, num, DEF_row_num_26_EQ_0___d146, 1u);
	backing.DEF_row_num_26_EQ_0___d146 = DEF_row_num_26_EQ_0___d146;
      }
      ++num;
      if ((backing.DEF_v__h4088) != DEF_v__h4088)
      {
	vcd_write_val(sim_hdl, num, DEF_v__h4088, 6u);
	backing.DEF_v__h4088 = DEF_v__h4088;
      }
      ++num;
      if ((backing.DEF_x__h1126) != DEF_x__h1126)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h1126, 5u);
	backing.DEF_x__h1126 = DEF_x__h1126;
      }
      ++num;
      if ((backing.DEF_x__h2686) != DEF_x__h2686)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h2686, 6u);
	backing.DEF_x__h2686 = DEF_x__h2686;
      }
      ++num;
      if ((backing.DEF_x__h4587) != DEF_x__h4587)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h4587, 6u);
	backing.DEF_x__h4587 = DEF_x__h4587;
      }
      ++num;
      if ((backing.DEF_x__h4819) != DEF_x__h4819)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h4819, 5u);
	backing.DEF_x__h4819 = DEF_x__h4819;
      }
      ++num;
      if ((backing.DEF_x__h5005) != DEF_x__h5005)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h5005, 5u);
	backing.DEF_x__h5005 = DEF_x__h5005;
      }
      ++num;
      if ((backing.DEF_x__h5077) != DEF_x__h5077)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h5077, 6u);
	backing.DEF_x__h5077 = DEF_x__h5077;
      }
      ++num;
      if ((backing.DEF_x__h5087) != DEF_x__h5087)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h5087, 6u);
	backing.DEF_x__h5087 = DEF_x__h5087;
      }
      ++num;
      if ((backing.DEF_x__h5146) != DEF_x__h5146)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h5146, 32u);
	backing.DEF_x__h5146 = DEF_x__h5146;
      }
      ++num;
      if ((backing.DEF_y__h4262) != DEF_y__h4262)
      {
	vcd_write_val(sim_hdl, num, DEF_y__h4262, 6u);
	backing.DEF_y__h4262 = DEF_y__h4262;
      }
      ++num;
      if ((backing.DEF_y__h4586) != DEF_y__h4586)
      {
	vcd_write_val(sim_hdl, num, DEF_y__h4586, 6u);
	backing.DEF_y__h4586 = DEF_y__h4586;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_b__h1524, 3u);
      backing.DEF_b__h1524 = DEF_b__h1524;
      vcd_write_val(sim_hdl, num++, DEF_b__h3084, 3u);
      backing.DEF_b__h3084 = DEF_b__h3084;
      vcd_write_val(sim_hdl, num++, DEF_lut_nnz_serverAdapter_cnt_1_whas____d20, 1u);
      backing.DEF_lut_nnz_serverAdapter_cnt_1_whas____d20 = DEF_lut_nnz_serverAdapter_cnt_1_whas____d20;
      vcd_write_val(sim_hdl, num++, DEF_lut_nnz_serverAdapter_cnt_2_whas____d21, 1u);
      backing.DEF_lut_nnz_serverAdapter_cnt_2_whas____d21 = DEF_lut_nnz_serverAdapter_cnt_2_whas____d21;
      vcd_write_val(sim_hdl, num++, DEF_lut_nnz_serverAdapter_cnt_3_whas____d23, 1u);
      backing.DEF_lut_nnz_serverAdapter_cnt_3_whas____d23 = DEF_lut_nnz_serverAdapter_cnt_3_whas____d23;
      vcd_write_val(sim_hdl, num++, DEF_lut_nnz_serverAdapter_s1_0_BIT_0___d51, 1u);
      backing.DEF_lut_nnz_serverAdapter_s1_0_BIT_0___d51 = DEF_lut_nnz_serverAdapter_s1_0_BIT_0___d51;
      vcd_write_val(sim_hdl, num++, DEF_lut_nnz_serverAdapter_s1___d50, 2u);
      backing.DEF_lut_nnz_serverAdapter_s1___d50 = DEF_lut_nnz_serverAdapter_s1___d50;
      vcd_write_val(sim_hdl, num++, DEF_lut_row_serverAdapter_cnt_1_whas____d79, 1u);
      backing.DEF_lut_row_serverAdapter_cnt_1_whas____d79 = DEF_lut_row_serverAdapter_cnt_1_whas____d79;
      vcd_write_val(sim_hdl, num++, DEF_lut_row_serverAdapter_cnt_2_whas____d80, 1u);
      backing.DEF_lut_row_serverAdapter_cnt_2_whas____d80 = DEF_lut_row_serverAdapter_cnt_2_whas____d80;
      vcd_write_val(sim_hdl, num++, DEF_lut_row_serverAdapter_cnt_3_whas____d82, 1u);
      backing.DEF_lut_row_serverAdapter_cnt_3_whas____d82 = DEF_lut_row_serverAdapter_cnt_3_whas____d82;
      vcd_write_val(sim_hdl, num++, DEF_lut_row_serverAdapter_outData_outData_wget__30_ETC___d132, 1u);
      backing.DEF_lut_row_serverAdapter_outData_outData_wget__30_ETC___d132 = DEF_lut_row_serverAdapter_outData_outData_wget__30_ETC___d132;
      vcd_write_val(sim_hdl, num++, DEF_lut_row_serverAdapter_s1_09_BIT_0___d110, 1u);
      backing.DEF_lut_row_serverAdapter_s1_09_BIT_0___d110 = DEF_lut_row_serverAdapter_s1_09_BIT_0___d110;
      vcd_write_val(sim_hdl, num++, DEF_lut_row_serverAdapter_s1___d109, 2u);
      backing.DEF_lut_row_serverAdapter_s1___d109 = DEF_lut_row_serverAdapter_s1___d109;
      vcd_write_val(sim_hdl, num++, DEF_nz_num_41_EQ_row_end_43_PLUS_1_44___d145, 1u);
      backing.DEF_nz_num_41_EQ_row_end_43_PLUS_1_44___d145 = DEF_nz_num_41_EQ_row_end_43_PLUS_1_44___d145;
      vcd_write_val(sim_hdl, num++, DEF_nz_num_41_ULT_row_end_43___d150, 1u);
      backing.DEF_nz_num_41_ULT_row_end_43___d150 = DEF_nz_num_41_ULT_row_end_43___d150;
      vcd_write_val(sim_hdl, num++, DEF_row_num_26_EQ_0___d146, 1u);
      backing.DEF_row_num_26_EQ_0___d146 = DEF_row_num_26_EQ_0___d146;
      vcd_write_val(sim_hdl, num++, DEF_v__h4088, 6u);
      backing.DEF_v__h4088 = DEF_v__h4088;
      vcd_write_val(sim_hdl, num++, DEF_x__h1126, 5u);
      backing.DEF_x__h1126 = DEF_x__h1126;
      vcd_write_val(sim_hdl, num++, DEF_x__h2686, 6u);
      backing.DEF_x__h2686 = DEF_x__h2686;
      vcd_write_val(sim_hdl, num++, DEF_x__h4587, 6u);
      backing.DEF_x__h4587 = DEF_x__h4587;
      vcd_write_val(sim_hdl, num++, DEF_x__h4819, 5u);
      backing.DEF_x__h4819 = DEF_x__h4819;
      vcd_write_val(sim_hdl, num++, DEF_x__h5005, 5u);
      backing.DEF_x__h5005 = DEF_x__h5005;
      vcd_write_val(sim_hdl, num++, DEF_x__h5077, 6u);
      backing.DEF_x__h5077 = DEF_x__h5077;
      vcd_write_val(sim_hdl, num++, DEF_x__h5087, 6u);
      backing.DEF_x__h5087 = DEF_x__h5087;
      vcd_write_val(sim_hdl, num++, DEF_x__h5146, 32u);
      backing.DEF_x__h5146 = DEF_x__h5146;
      vcd_write_val(sim_hdl, num++, DEF_y__h4262, 6u);
      backing.DEF_y__h4262 = DEF_y__h4262;
      vcd_write_val(sim_hdl, num++, DEF_y__h4586, 6u);
      backing.DEF_y__h4586 = DEF_y__h4586;
    }
}

void MOD_mkCsrBMVM::vcd_prims(tVCDDumpType dt, MOD_mkCsrBMVM &backing)
{
  INST_in.dump_VCD(dt, backing.INST_in);
  INST_in_fifo.dump_VCD(dt, backing.INST_in_fifo);
  INST_lut_nnz_memory.dump_VCD(dt, backing.INST_lut_nnz_memory);
  INST_lut_nnz_serverAdapter_cnt.dump_VCD(dt, backing.INST_lut_nnz_serverAdapter_cnt);
  INST_lut_nnz_serverAdapter_cnt_1.dump_VCD(dt, backing.INST_lut_nnz_serverAdapter_cnt_1);
  INST_lut_nnz_serverAdapter_cnt_2.dump_VCD(dt, backing.INST_lut_nnz_serverAdapter_cnt_2);
  INST_lut_nnz_serverAdapter_cnt_3.dump_VCD(dt, backing.INST_lut_nnz_serverAdapter_cnt_3);
  INST_lut_nnz_serverAdapter_outDataCore.dump_VCD(dt, backing.INST_lut_nnz_serverAdapter_outDataCore);
  INST_lut_nnz_serverAdapter_outData_deqCalled.dump_VCD(dt,
							backing.INST_lut_nnz_serverAdapter_outData_deqCalled);
  INST_lut_nnz_serverAdapter_outData_enqData.dump_VCD(dt,
						      backing.INST_lut_nnz_serverAdapter_outData_enqData);
  INST_lut_nnz_serverAdapter_outData_outData.dump_VCD(dt,
						      backing.INST_lut_nnz_serverAdapter_outData_outData);
  INST_lut_nnz_serverAdapter_s1.dump_VCD(dt, backing.INST_lut_nnz_serverAdapter_s1);
  INST_lut_nnz_serverAdapter_s1_1.dump_VCD(dt, backing.INST_lut_nnz_serverAdapter_s1_1);
  INST_lut_nnz_serverAdapter_writeWithResp.dump_VCD(dt,
						    backing.INST_lut_nnz_serverAdapter_writeWithResp);
  INST_lut_row_memory.dump_VCD(dt, backing.INST_lut_row_memory);
  INST_lut_row_serverAdapter_cnt.dump_VCD(dt, backing.INST_lut_row_serverAdapter_cnt);
  INST_lut_row_serverAdapter_cnt_1.dump_VCD(dt, backing.INST_lut_row_serverAdapter_cnt_1);
  INST_lut_row_serverAdapter_cnt_2.dump_VCD(dt, backing.INST_lut_row_serverAdapter_cnt_2);
  INST_lut_row_serverAdapter_cnt_3.dump_VCD(dt, backing.INST_lut_row_serverAdapter_cnt_3);
  INST_lut_row_serverAdapter_outDataCore.dump_VCD(dt, backing.INST_lut_row_serverAdapter_outDataCore);
  INST_lut_row_serverAdapter_outData_deqCalled.dump_VCD(dt,
							backing.INST_lut_row_serverAdapter_outData_deqCalled);
  INST_lut_row_serverAdapter_outData_enqData.dump_VCD(dt,
						      backing.INST_lut_row_serverAdapter_outData_enqData);
  INST_lut_row_serverAdapter_outData_outData.dump_VCD(dt,
						      backing.INST_lut_row_serverAdapter_outData_outData);
  INST_lut_row_serverAdapter_s1.dump_VCD(dt, backing.INST_lut_row_serverAdapter_s1);
  INST_lut_row_serverAdapter_s1_1.dump_VCD(dt, backing.INST_lut_row_serverAdapter_s1_1);
  INST_lut_row_serverAdapter_writeWithResp.dump_VCD(dt,
						    backing.INST_lut_row_serverAdapter_writeWithResp);
  INST_nz_num.dump_VCD(dt, backing.INST_nz_num);
  INST_out.dump_VCD(dt, backing.INST_out);
  INST_out_fifo.dump_VCD(dt, backing.INST_out_fifo);
  INST_row_end.dump_VCD(dt, backing.INST_row_end);
  INST_row_num.dump_VCD(dt, backing.INST_row_num);
  INST_row_start.dump_VCD(dt, backing.INST_row_start);
  INST_state.dump_VCD(dt, backing.INST_state);
}
