/*
 * Generated by Bluespec Compiler, version 2014.05.C (build 33930, 2014-05-28)
 * 
 * On Thu May  3 17:08:20 IST 2018
 * 
 */
#include "bluesim_primitives.h"
#include "mkEllBMVM.h"


/* String declarations */
static std::string const __str_literal_1("../ELL_BMVM/LUT/ell0.mem", 24u);
static std::string const __str_literal_2("ERROR: %m: mkBRAMSeverAdapter overrun", 37u);
static std::string const __str_literal_3("Request Recevived %s", 20u);
static std::string const __str_literal_4("Row Entry Read: %0b", 19u);


/* Constructor */
MOD_mkEllBMVM::MOD_mkEllBMVM(tSimStateHdl simHdl,
			     char const *name,
			     Module *parent,
			     tUInt32 ARG_lut_num)
  : Module(simHdl, name, parent),
    __clk_handle_0(BAD_CLOCK_HANDLE),
    PARAM_lut_num(ARG_lut_num),
    INST_in(simHdl, "in", this, 32u, 0u, (tUInt8)0u),
    INST_in_fifo(simHdl, "in_fifo", this, 32u, 2u, 1u, 0u),
    INST_lut_memory(simHdl,
		    "lut_memory",
		    this,
		    __str_literal_1,
		    (tUInt8)0u,
		    5u,
		    26u,
		    (tUInt8)32u,
		    (tUInt8)1u,
		    1u),
    INST_lut_serverAdapter_cnt(simHdl, "lut_serverAdapter_cnt", this, 3u, (tUInt8)0u, (tUInt8)0u),
    INST_lut_serverAdapter_cnt_1(simHdl, "lut_serverAdapter_cnt_1", this, 3u, (tUInt8)0u),
    INST_lut_serverAdapter_cnt_2(simHdl, "lut_serverAdapter_cnt_2", this, 3u, (tUInt8)0u),
    INST_lut_serverAdapter_cnt_3(simHdl, "lut_serverAdapter_cnt_3", this, 3u, (tUInt8)0u),
    INST_lut_serverAdapter_outDataCore(simHdl, "lut_serverAdapter_outDataCore", this, 26u, 3u, 1u, 0u),
    INST_lut_serverAdapter_outData_deqCalled(simHdl, "lut_serverAdapter_outData_deqCalled", this, 0u),
    INST_lut_serverAdapter_outData_enqData(simHdl,
					   "lut_serverAdapter_outData_enqData",
					   this,
					   26u,
					   (tUInt8)0u),
    INST_lut_serverAdapter_outData_outData(simHdl,
					   "lut_serverAdapter_outData_outData",
					   this,
					   26u,
					   (tUInt8)0u),
    INST_lut_serverAdapter_s1(simHdl, "lut_serverAdapter_s1", this, 2u, (tUInt8)0u, (tUInt8)0u),
    INST_lut_serverAdapter_s1_1(simHdl, "lut_serverAdapter_s1_1", this, 2u, (tUInt8)0u),
    INST_lut_serverAdapter_writeWithResp(simHdl,
					 "lut_serverAdapter_writeWithResp",
					 this,
					 2u,
					 (tUInt8)0u),
    INST_out(simHdl, "out", this, 32u, 0u, (tUInt8)0u),
    INST_out_fifo(simHdl, "out_fifo", this, 32u, 2u, 1u, 0u),
    INST_row_num(simHdl, "row_num", this, 5u, (tUInt8)0u, (tUInt8)0u),
    INST_state(simHdl, "state", this, 2u, (tUInt8)0u, (tUInt8)0u),
    PORT_RST_N((tUInt8)1u)
{
  symbol_count = 35u;
  symbols = new tSym[symbol_count];
  init_symbols_0();
}


/* Symbol init fns */

void MOD_mkEllBMVM::init_symbols_0()
{
  init_symbol(&symbols[0u], "b__h1362", SYM_DEF, &DEF_b__h1362, 3u);
  init_symbol(&symbols[1u], "in", SYM_MODULE, &INST_in);
  init_symbol(&symbols[2u], "in_fifo", SYM_MODULE, &INST_in_fifo);
  init_symbol(&symbols[3u], "lut_memory", SYM_MODULE, &INST_lut_memory);
  init_symbol(&symbols[4u], "lut_num", SYM_PARAM, (void *)(&PARAM_lut_num), 32u);
  init_symbol(&symbols[5u], "lut_serverAdapter_cnt", SYM_MODULE, &INST_lut_serverAdapter_cnt);
  init_symbol(&symbols[6u], "lut_serverAdapter_cnt_1", SYM_MODULE, &INST_lut_serverAdapter_cnt_1);
  init_symbol(&symbols[7u], "lut_serverAdapter_cnt_2", SYM_MODULE, &INST_lut_serverAdapter_cnt_2);
  init_symbol(&symbols[8u], "lut_serverAdapter_cnt_3", SYM_MODULE, &INST_lut_serverAdapter_cnt_3);
  init_symbol(&symbols[9u],
	      "lut_serverAdapter_outData_deqCalled",
	      SYM_MODULE,
	      &INST_lut_serverAdapter_outData_deqCalled);
  init_symbol(&symbols[10u],
	      "lut_serverAdapter_outData_enqData",
	      SYM_MODULE,
	      &INST_lut_serverAdapter_outData_enqData);
  init_symbol(&symbols[11u],
	      "lut_serverAdapter_outData_outData",
	      SYM_MODULE,
	      &INST_lut_serverAdapter_outData_outData);
  init_symbol(&symbols[12u],
	      "lut_serverAdapter_outDataCore",
	      SYM_MODULE,
	      &INST_lut_serverAdapter_outDataCore);
  init_symbol(&symbols[13u], "lut_serverAdapter_s1", SYM_MODULE, &INST_lut_serverAdapter_s1);
  init_symbol(&symbols[14u], "lut_serverAdapter_s1_1", SYM_MODULE, &INST_lut_serverAdapter_s1_1);
  init_symbol(&symbols[15u],
	      "lut_serverAdapter_writeWithResp",
	      SYM_MODULE,
	      &INST_lut_serverAdapter_writeWithResp);
  init_symbol(&symbols[16u], "out", SYM_MODULE, &INST_out);
  init_symbol(&symbols[17u], "out_fifo", SYM_MODULE, &INST_out_fifo);
  init_symbol(&symbols[18u], "RL_complete", SYM_RULE);
  init_symbol(&symbols[19u], "RL_initiateBMVM", SYM_RULE);
  init_symbol(&symbols[20u], "RL_lut_serverAdapter_cnt_finalAdd", SYM_RULE);
  init_symbol(&symbols[21u], "RL_lut_serverAdapter_moveToOutFIFO", SYM_RULE);
  init_symbol(&symbols[22u], "RL_lut_serverAdapter_outData_deqOnly", SYM_RULE);
  init_symbol(&symbols[23u], "RL_lut_serverAdapter_outData_enqAndDeq", SYM_RULE);
  init_symbol(&symbols[24u], "RL_lut_serverAdapter_outData_enqOnly", SYM_RULE);
  init_symbol(&symbols[25u], "RL_lut_serverAdapter_outData_setFirstCore", SYM_RULE);
  init_symbol(&symbols[26u], "RL_lut_serverAdapter_outData_setFirstEnq", SYM_RULE);
  init_symbol(&symbols[27u], "RL_lut_serverAdapter_overRun", SYM_RULE);
  init_symbol(&symbols[28u], "RL_lut_serverAdapter_s1__dreg_update", SYM_RULE);
  init_symbol(&symbols[29u], "RL_lut_serverAdapter_stageReadResponseAlways", SYM_RULE);
  init_symbol(&symbols[30u], "RL_receive", SYM_RULE);
  init_symbol(&symbols[31u], "row_num", SYM_MODULE, &INST_row_num);
  init_symbol(&symbols[32u], "state", SYM_MODULE, &INST_state);
  init_symbol(&symbols[33u], "x__h9405", SYM_DEF, &DEF_x__h9405, 5u);
  init_symbol(&symbols[34u], "x__h9411", SYM_DEF, &DEF_x__h9411, 2u);
}


/* Rule actions */

void MOD_mkEllBMVM::RL_lut_serverAdapter_outData_setFirstCore()
{
  tUInt32 DEF_x__h873;
  DEF_x__h873 = INST_lut_serverAdapter_outDataCore.METH_first();
  INST_lut_serverAdapter_outData_outData.METH_wset(DEF_x__h873);
}

void MOD_mkEllBMVM::RL_lut_serverAdapter_outData_setFirstEnq()
{
  DEF_x__h964 = INST_lut_serverAdapter_outData_enqData.METH_wget();
  INST_lut_serverAdapter_outData_outData.METH_wset(DEF_x__h964);
}

void MOD_mkEllBMVM::RL_lut_serverAdapter_outData_enqOnly()
{
  DEF_x__h964 = INST_lut_serverAdapter_outData_enqData.METH_wget();
  INST_lut_serverAdapter_outDataCore.METH_enq(DEF_x__h964);
}

void MOD_mkEllBMVM::RL_lut_serverAdapter_outData_deqOnly()
{
  INST_lut_serverAdapter_outDataCore.METH_deq();
}

void MOD_mkEllBMVM::RL_lut_serverAdapter_outData_enqAndDeq()
{
  DEF_x__h964 = INST_lut_serverAdapter_outData_enqData.METH_wget();
  INST_lut_serverAdapter_outDataCore.METH_enq(DEF_x__h964);
  INST_lut_serverAdapter_outDataCore.METH_deq();
}

void MOD_mkEllBMVM::RL_lut_serverAdapter_cnt_finalAdd()
{
  tUInt8 DEF_IF_lut_serverAdapter_cnt_3_whas__3_THEN_lut_se_ETC___d33;
  tUInt8 DEF_b__h1342;
  DEF_b__h1342 = INST_lut_serverAdapter_cnt_3.METH_wget();
  DEF_b__h1362 = INST_lut_serverAdapter_cnt.METH_read();
  DEF_lut_serverAdapter_cnt_3_whas____d23 = INST_lut_serverAdapter_cnt_3.METH_whas();
  DEF_lut_serverAdapter_cnt_2_whas____d21 = INST_lut_serverAdapter_cnt_2.METH_whas();
  DEF_lut_serverAdapter_cnt_1_whas____d20 = INST_lut_serverAdapter_cnt_1.METH_whas();
  DEF_IF_lut_serverAdapter_cnt_3_whas__3_THEN_lut_se_ETC___d33 = DEF_lut_serverAdapter_cnt_3_whas____d23 ? DEF_b__h1342 : (tUInt8)7u & (((tUInt8)7u & (DEF_b__h1362 + (DEF_lut_serverAdapter_cnt_1_whas____d20 ? INST_lut_serverAdapter_cnt_1.METH_wget() : (tUInt8)0u))) + (DEF_lut_serverAdapter_cnt_2_whas____d21 ? INST_lut_serverAdapter_cnt_2.METH_wget() : (tUInt8)0u));
  INST_lut_serverAdapter_cnt.METH_write(DEF_IF_lut_serverAdapter_cnt_3_whas__3_THEN_lut_se_ETC___d33);
}

void MOD_mkEllBMVM::RL_lut_serverAdapter_s1__dreg_update()
{
  tUInt8 DEF_lut_serverAdapter_s1_1_whas__4_AND_0_OR_lut_se_ETC___d42;
  tUInt8 DEF_IF_lut_serverAdapter_s1_1_wget__5_BIT_1_6_THEN_ETC___d40;
  tUInt8 DEF_lut_serverAdapter_s1_1_wget__5_BIT_0___d39;
  tUInt8 DEF_lut_serverAdapter_s1_1_wget__5_BIT_1___d36;
  tUInt8 DEF_lut_serverAdapter_s1_1_whas____d34;
  tUInt8 DEF_lut_serverAdapter_s1_1_wget____d35;
  DEF_lut_serverAdapter_s1_1_wget____d35 = INST_lut_serverAdapter_s1_1.METH_wget();
  DEF_lut_serverAdapter_s1_1_whas____d34 = INST_lut_serverAdapter_s1_1.METH_whas();
  DEF_lut_serverAdapter_s1_1_wget__5_BIT_1___d36 = (tUInt8)(DEF_lut_serverAdapter_s1_1_wget____d35 >> 1u);
  DEF_lut_serverAdapter_s1_1_wget__5_BIT_0___d39 = (tUInt8)((tUInt8)1u & DEF_lut_serverAdapter_s1_1_wget____d35);
  DEF_IF_lut_serverAdapter_s1_1_wget__5_BIT_1_6_THEN_ETC___d40 = DEF_lut_serverAdapter_s1_1_wget__5_BIT_1___d36 ? DEF_lut_serverAdapter_s1_1_wget__5_BIT_0___d39 : DEF_lut_serverAdapter_s1_1_wget__5_BIT_0___d39;
  DEF_lut_serverAdapter_s1_1_whas__4_AND_0_OR_lut_se_ETC___d42 = (tUInt8)3u & (((DEF_lut_serverAdapter_s1_1_whas____d34 && DEF_lut_serverAdapter_s1_1_wget__5_BIT_1___d36) << 1u) | (DEF_lut_serverAdapter_s1_1_whas____d34 ? DEF_IF_lut_serverAdapter_s1_1_wget__5_BIT_1_6_THEN_ETC___d40 : DEF_IF_lut_serverAdapter_s1_1_wget__5_BIT_1_6_THEN_ETC___d40));
  INST_lut_serverAdapter_s1.METH_write(DEF_lut_serverAdapter_s1_1_whas__4_AND_0_OR_lut_se_ETC___d42);
}

void MOD_mkEllBMVM::RL_lut_serverAdapter_stageReadResponseAlways()
{
  tUInt8 DEF_NOT_lut_serverAdapter_writeWithResp_wget__4_BI_ETC___d48;
  tUInt8 DEF__1_CONCAT_NOT_lut_serverAdapter_writeWithResp_w_ETC___d49;
  tUInt8 DEF_ab_BIT_0___h1865;
  tUInt8 DEF_ab_BIT_1___h1859;
  tUInt8 DEF_ab__h1851;
  DEF_ab__h1851 = INST_lut_serverAdapter_writeWithResp.METH_wget();
  DEF_ab_BIT_1___h1859 = (tUInt8)(DEF_ab__h1851 >> 1u);
  DEF_ab_BIT_0___h1865 = (tUInt8)((tUInt8)1u & DEF_ab__h1851);
  DEF_NOT_lut_serverAdapter_writeWithResp_wget__4_BI_ETC___d48 = !DEF_ab_BIT_1___h1859 || DEF_ab_BIT_0___h1865;
  DEF__1_CONCAT_NOT_lut_serverAdapter_writeWithResp_w_ETC___d49 = (tUInt8)3u & (((tUInt8)1u << 1u) | DEF_NOT_lut_serverAdapter_writeWithResp_wget__4_BI_ETC___d48);
  INST_lut_serverAdapter_s1_1.METH_wset(DEF__1_CONCAT_NOT_lut_serverAdapter_writeWithResp_w_ETC___d49);
  if (DEF_NOT_lut_serverAdapter_writeWithResp_wget__4_BI_ETC___d48)
    INST_lut_serverAdapter_cnt_1.METH_wset((tUInt8)1u);
}

void MOD_mkEllBMVM::RL_lut_serverAdapter_moveToOutFIFO()
{
  tUInt32 DEF_v__h1968;
  DEF_v__h1968 = INST_lut_memory.METH_read();
  DEF_lut_serverAdapter_s1___d50 = INST_lut_serverAdapter_s1.METH_read();
  DEF_lut_serverAdapter_s1_0_BIT_0___d51 = (tUInt8)((tUInt8)1u & DEF_lut_serverAdapter_s1___d50);
  if (DEF_lut_serverAdapter_s1_0_BIT_0___d51)
    INST_lut_serverAdapter_outData_enqData.METH_wset(DEF_v__h1968);
}

void MOD_mkEllBMVM::RL_lut_serverAdapter_overRun()
{
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s", &__str_literal_2);
}

void MOD_mkEllBMVM::RL_initiateBMVM()
{
  tUInt32 DEF_x__h2064;
  DEF_x__h9405 = INST_row_num.METH_read();
  DEF_x__h2064 = INST_in_fifo.METH_first();
  DEF_x__h9401 = (tUInt8)31u & (DEF_x__h9405 + (tUInt8)1u);
  INST_in.METH_write(DEF_x__h2064);
  INST_in_fifo.METH_deq();
  INST_lut_memory.METH_put((tUInt8)0u, DEF_x__h9405, 44739242u);
  INST_lut_serverAdapter_writeWithResp.METH_wset((tUInt8)0u);
  if (!(PORT_RST_N == (tUInt8)0u))
    dollar_display(sim_hdl, this, "s,s", &__str_literal_3, &__str_literal_1);
  INST_state.METH_write((tUInt8)1u);
  INST_row_num.METH_write(DEF_x__h9401);
}

void MOD_mkEllBMVM::RL_receive()
{
  tUInt8 DEF_x__h6364;
  tUInt8 DEF_x__h6362;
  tUInt8 DEF_x__h6360;
  tUInt8 DEF_x__h6704;
  tUInt8 DEF_x__h6702;
  tUInt8 DEF_x__h6700;
  tUInt8 DEF_y__h4437;
  tUInt8 DEF_x__h7048;
  tUInt8 DEF_x__h7046;
  tUInt8 DEF_x__h7044;
  tUInt8 DEF_y__h6078;
  tUInt8 DEF_x__h9033;
  tUInt8 DEF_x__h9031;
  tUInt8 DEF_x__h9029;
  tUInt8 DEF_y__h7719;
  tUInt8 DEF_y__h2724;
  tUInt8 DEF_x__h2723;
  tUInt8 DEF_y__h2709;
  tUInt8 DEF_x__h2708;
  tUInt8 DEF_y__h2694;
  tUInt8 DEF_x__h2693;
  tUInt8 DEF_y__h2679;
  tUInt8 DEF_x__h2678;
  tUInt8 DEF_x__h9374;
  tUInt32 DEF_x__h2619;
  tUInt32 DEF_y__h9395;
  tUInt8 DEF_IF_state_3_EQ_2_0_THEN_3_ELSE_2___d80;
  tUInt32 DEF_x__h2605;
  tUInt8 DEF_x__h2795;
  tUInt8 DEF_x__h4436;
  tUInt8 DEF_x__h6077;
  tUInt8 DEF_x__h7718;
  tUInt8 DEF_x__h6366;
  tUInt8 DEF_y__h6367;
  tUInt8 DEF_y__h6365;
  tUInt8 DEF_y__h6363;
  tUInt8 DEF_y__h6361;
  tUInt8 DEF_x__h6706;
  tUInt8 DEF_y__h6707;
  tUInt8 DEF_y__h6705;
  tUInt8 DEF_y__h6703;
  tUInt8 DEF_y__h6701;
  tUInt8 DEF_x__h7050;
  tUInt8 DEF_y__h7051;
  tUInt8 DEF_y__h7049;
  tUInt8 DEF_y__h7047;
  tUInt8 DEF_y__h7045;
  tUInt8 DEF_x__h9035;
  tUInt8 DEF_y__h9036;
  tUInt8 DEF_y__h9034;
  tUInt8 DEF_y__h9032;
  tUInt8 DEF_y__h9030;
  tUInt8 DEF_row_part__h2710;
  tUInt8 DEF_row_part__h2695;
  tUInt8 DEF_row_part__h2680;
  tUInt8 DEF_row_part__h2665;
  tUInt8 DEF_i__h2751;
  tUInt32 DEF_lut_serverAdapter_outData_outData_wget____d84;
  tUInt32 DEF_bs__h7721;
  tUInt8 DEF_NOT_row_num_7_EQ_0_9_1_OR_NOT_state_3_EQ_2_0_2___d83;
  DEF_x__h9405 = INST_row_num.METH_read();
  DEF_x__h9431 = INST_out.METH_read();
  DEF_bs__h7721 = INST_in.METH_read();
  DEF_lut_serverAdapter_outData_outData_wget____d84 = INST_lut_serverAdapter_outData_outData.METH_wget();
  DEF_x__h9411 = INST_state.METH_read();
  DEF_i__h2751 = (tUInt8)((tUInt8)31u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 20u));
  DEF_row_part__h2665 = (tUInt8)((tUInt8)31u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 15u));
  DEF_row_part__h2680 = (tUInt8)((tUInt8)31u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 10u));
  DEF_row_part__h2695 = (tUInt8)((tUInt8)31u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 5u));
  DEF_row_part__h2710 = (tUInt8)((tUInt8)31u & DEF_lut_serverAdapter_outData_outData_wget____d84);
  DEF_y__h9032 = (tUInt8)((tUInt8)1u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 18u));
  DEF_y__h9030 = (tUInt8)((tUInt8)1u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 19u));
  DEF_y__h9034 = (tUInt8)((tUInt8)1u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 17u));
  DEF_y__h9036 = (tUInt8)((tUInt8)1u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 16u));
  DEF_x__h9035 = (tUInt8)((tUInt8)1u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 15u));
  DEF_y__h7047 = (tUInt8)((tUInt8)1u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 13u));
  DEF_y__h7045 = (tUInt8)((tUInt8)1u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 14u));
  DEF_y__h7049 = (tUInt8)((tUInt8)1u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 12u));
  DEF_y__h7051 = (tUInt8)((tUInt8)1u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 11u));
  DEF_x__h7050 = (tUInt8)((tUInt8)1u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 10u));
  DEF_y__h6703 = (tUInt8)((tUInt8)1u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 8u));
  DEF_y__h6701 = (tUInt8)((tUInt8)1u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 9u));
  DEF_y__h6705 = (tUInt8)((tUInt8)1u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 7u));
  DEF_y__h6707 = (tUInt8)((tUInt8)1u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 6u));
  DEF_y__h6361 = (tUInt8)((tUInt8)1u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 4u));
  DEF_x__h6706 = (tUInt8)((tUInt8)1u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 5u));
  DEF_y__h6363 = (tUInt8)((tUInt8)1u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 3u));
  DEF_y__h6365 = (tUInt8)((tUInt8)1u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 2u));
  DEF_x__h6366 = (tUInt8)((tUInt8)1u & DEF_lut_serverAdapter_outData_outData_wget____d84);
  DEF_y__h6367 = (tUInt8)((tUInt8)1u & (DEF_lut_serverAdapter_outData_outData_wget____d84 >> 1u));
  DEF_x__h7718 = primExtract8(1u,
			      32u,
			      (tUInt32)(DEF_bs__h7721),
			      5u,
			      (tUInt8)(DEF_row_part__h2665),
			      5u,
			      (tUInt8)(DEF_row_part__h2665));
  DEF_x__h6077 = primExtract8(1u,
			      32u,
			      (tUInt32)(DEF_bs__h7721),
			      5u,
			      (tUInt8)(DEF_row_part__h2680),
			      5u,
			      (tUInt8)(DEF_row_part__h2680));
  DEF_x__h4436 = primExtract8(1u,
			      32u,
			      (tUInt32)(DEF_bs__h7721),
			      5u,
			      (tUInt8)(DEF_row_part__h2695),
			      5u,
			      (tUInt8)(DEF_row_part__h2695));
  DEF_x__h2795 = primExtract8(1u,
			      32u,
			      (tUInt32)(DEF_bs__h7721),
			      5u,
			      (tUInt8)(DEF_row_part__h2710),
			      5u,
			      (tUInt8)(DEF_row_part__h2710));
  DEF_state_3_EQ_2___d70 = DEF_x__h9411 == (tUInt8)2u;
  DEF_IF_state_3_EQ_2_0_THEN_3_ELSE_2___d80 = DEF_state_3_EQ_2___d70 ? (tUInt8)3u : (tUInt8)2u;
  DEF_row_num_7_EQ_0___d69 = DEF_x__h9405 == (tUInt8)0u;
  DEF_NOT_row_num_7_EQ_0_9_1_OR_NOT_state_3_EQ_2_0_2___d83 = !DEF_row_num_7_EQ_0___d69 || !DEF_state_3_EQ_2___d70;
  DEF_x__h9374 = (tUInt8)31u & (DEF_x__h9405 - (tUInt8)1u);
  DEF_x__h2619 = primShiftL32(32u, 32u, 1u, 5u, (tUInt8)(DEF_x__h9374));
  DEF_y__h9395 = ~DEF_x__h2619;
  DEF_x__h2723 = ((tUInt8)(DEF_lut_serverAdapter_outData_outData_wget____d84 >> 25u)) & primExtract8(1u,
												     32u,
												     (tUInt32)(DEF_bs__h7721),
												     5u,
												     (tUInt8)(DEF_i__h2751),
												     5u,
												     (tUInt8)(DEF_i__h2751));
  DEF_x__h9033 = DEF_x__h9035 | DEF_y__h9036;
  DEF_x__h9031 = DEF_x__h9033 | DEF_y__h9034;
  DEF_x__h9029 = DEF_x__h9031 | DEF_y__h9032;
  DEF_y__h7719 = DEF_x__h9029 | DEF_y__h9030;
  DEF_y__h2679 = DEF_x__h7718 & DEF_y__h7719;
  DEF_x__h7048 = DEF_x__h7050 | DEF_y__h7051;
  DEF_x__h7046 = DEF_x__h7048 | DEF_y__h7049;
  DEF_x__h7044 = DEF_x__h7046 | DEF_y__h7047;
  DEF_y__h6078 = DEF_x__h7044 | DEF_y__h7045;
  DEF_y__h2694 = DEF_x__h6077 & DEF_y__h6078;
  DEF_x__h9401 = (tUInt8)31u & (DEF_x__h9405 + (tUInt8)1u);
  DEF_x__h6704 = DEF_x__h6706 | DEF_y__h6707;
  DEF_x__h6702 = DEF_x__h6704 | DEF_y__h6705;
  DEF_x__h6700 = DEF_x__h6702 | DEF_y__h6703;
  DEF_y__h4437 = DEF_x__h6700 | DEF_y__h6701;
  DEF_y__h2709 = DEF_x__h4436 & DEF_y__h4437;
  DEF_x__h6364 = DEF_x__h6366 | DEF_y__h6367;
  DEF_x__h6362 = DEF_x__h6364 | DEF_y__h6365;
  DEF_x__h6360 = DEF_x__h6362 | DEF_y__h6363;
  DEF_y__h2724 = DEF_x__h2795 & ((tUInt8)((tUInt8)1u & (DEF_x__h6360 | DEF_y__h6361 ? (tUInt8)1u : (tUInt8)0u)));
  DEF_x__h2708 = DEF_x__h2723 ^ DEF_y__h2724;
  DEF_x__h2693 = DEF_x__h2708 ^ DEF_y__h2709;
  DEF_x__h2678 = DEF_x__h2693 ^ DEF_y__h2694;
  DEF_x__h2605 = DEF_x__h2678 ^ DEF_y__h2679 ? DEF_x__h9431 | DEF_x__h2619 : DEF_x__h9431 & DEF_y__h9395;
  if (DEF_row_num_7_EQ_0___d69)
    INST_state.METH_write(DEF_IF_state_3_EQ_2_0_THEN_3_ELSE_2___d80);
  if (DEF_NOT_row_num_7_EQ_0_9_1_OR_NOT_state_3_EQ_2_0_2___d83)
    INST_lut_memory.METH_put((tUInt8)0u, DEF_x__h9405, 44739242u);
  if (DEF_NOT_row_num_7_EQ_0_9_1_OR_NOT_state_3_EQ_2_0_2___d83)
    INST_lut_serverAdapter_writeWithResp.METH_wset((tUInt8)0u);
  if (DEF_NOT_row_num_7_EQ_0_9_1_OR_NOT_state_3_EQ_2_0_2___d83)
    INST_lut_serverAdapter_outData_deqCalled.METH_wset();
  if (DEF_NOT_row_num_7_EQ_0_9_1_OR_NOT_state_3_EQ_2_0_2___d83)
    INST_lut_serverAdapter_cnt_2.METH_wset((tUInt8)7u);
  if (!(PORT_RST_N == (tUInt8)0u))
    if (DEF_NOT_row_num_7_EQ_0_9_1_OR_NOT_state_3_EQ_2_0_2___d83)
      dollar_display(sim_hdl,
		     this,
		     "s,26",
		     &__str_literal_4,
		     DEF_lut_serverAdapter_outData_outData_wget____d84);
  if (DEF_NOT_row_num_7_EQ_0_9_1_OR_NOT_state_3_EQ_2_0_2___d83)
    INST_out.METH_write(DEF_x__h2605);
  if (DEF_NOT_row_num_7_EQ_0_9_1_OR_NOT_state_3_EQ_2_0_2___d83)
    INST_row_num.METH_write(DEF_x__h9401);
}

void MOD_mkEllBMVM::RL_complete()
{
  DEF_x__h9431 = INST_out.METH_read();
  INST_out_fifo.METH_enq(DEF_x__h9431);
  INST_state.METH_write((tUInt8)0u);
  INST_row_num.METH_write((tUInt8)0u);
}


/* Methods */

tUInt32 MOD_mkEllBMVM::METH_get()
{
  tUInt32 DEF_get__avValue1;
  tUInt32 PORT_get;
  DEF_get__avValue1 = INST_out_fifo.METH_first();
  PORT_get = DEF_get__avValue1;
  INST_out_fifo.METH_deq();
  return PORT_get;
}

tUInt8 MOD_mkEllBMVM::METH_RDY_get()
{
  tUInt8 PORT_RDY_get;
  tUInt8 DEF_CAN_FIRE_get;
  DEF_CAN_FIRE_get = INST_out_fifo.METH_i_notEmpty();
  PORT_RDY_get = DEF_CAN_FIRE_get;
  return PORT_RDY_get;
}

void MOD_mkEllBMVM::METH_put(tUInt32 ARG_put_x)
{
  INST_in_fifo.METH_enq(ARG_put_x);
}

tUInt8 MOD_mkEllBMVM::METH_RDY_put()
{
  tUInt8 PORT_RDY_put;
  tUInt8 DEF_CAN_FIRE_put;
  DEF_CAN_FIRE_put = INST_in_fifo.METH_i_notFull();
  PORT_RDY_put = DEF_CAN_FIRE_put;
  return PORT_RDY_put;
}


/* Reset routines */

void MOD_mkEllBMVM::reset_RST_N(tUInt8 ARG_rst_in)
{
  PORT_RST_N = ARG_rst_in;
  INST_state.reset_RST(ARG_rst_in);
  INST_row_num.reset_RST(ARG_rst_in);
  INST_out_fifo.reset_RST(ARG_rst_in);
  INST_out.reset_RST(ARG_rst_in);
  INST_lut_serverAdapter_s1.reset_RST(ARG_rst_in);
  INST_lut_serverAdapter_outDataCore.reset_RST(ARG_rst_in);
  INST_lut_serverAdapter_cnt.reset_RST(ARG_rst_in);
  INST_in_fifo.reset_RST(ARG_rst_in);
  INST_in.reset_RST(ARG_rst_in);
}


/* Static handles to reset routines */


/* Functions for the parent module to register its reset fns */


/* Functions to set the elaborated clock id */

void MOD_mkEllBMVM::set_clk_0(char const *s)
{
  __clk_handle_0 = bk_get_or_define_clock(sim_hdl, s);
}


/* State dumping routine */
void MOD_mkEllBMVM::dump_state(unsigned int indent)
{
  printf("%*s%s:\n", indent, "", inst_name);
  INST_in.dump_state(indent + 2u);
  INST_in_fifo.dump_state(indent + 2u);
  INST_lut_memory.dump_state(indent + 2u);
  INST_lut_serverAdapter_cnt.dump_state(indent + 2u);
  INST_lut_serverAdapter_cnt_1.dump_state(indent + 2u);
  INST_lut_serverAdapter_cnt_2.dump_state(indent + 2u);
  INST_lut_serverAdapter_cnt_3.dump_state(indent + 2u);
  INST_lut_serverAdapter_outDataCore.dump_state(indent + 2u);
  INST_lut_serverAdapter_outData_deqCalled.dump_state(indent + 2u);
  INST_lut_serverAdapter_outData_enqData.dump_state(indent + 2u);
  INST_lut_serverAdapter_outData_outData.dump_state(indent + 2u);
  INST_lut_serverAdapter_s1.dump_state(indent + 2u);
  INST_lut_serverAdapter_s1_1.dump_state(indent + 2u);
  INST_lut_serverAdapter_writeWithResp.dump_state(indent + 2u);
  INST_out.dump_state(indent + 2u);
  INST_out_fifo.dump_state(indent + 2u);
  INST_row_num.dump_state(indent + 2u);
  INST_state.dump_state(indent + 2u);
}


/* VCD dumping routines */

unsigned int MOD_mkEllBMVM::dump_VCD_defs(unsigned int levels)
{
  vcd_write_scope_start(sim_hdl, inst_name);
  vcd_num = vcd_reserve_ids(sim_hdl, 32u);
  unsigned int num = vcd_num;
  for (unsigned int clk = 0u; clk < bk_num_clocks(sim_hdl); ++clk)
    vcd_add_clock_def(sim_hdl, this, bk_clock_name(sim_hdl, clk), bk_clock_vcd_num(sim_hdl, clk));
  vcd_write_def(sim_hdl, bk_clock_vcd_num(sim_hdl, __clk_handle_0), "CLK", 1u);
  vcd_write_def(sim_hdl, num++, "RST_N", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "b__h1362", 3u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "lut_serverAdapter_cnt_1_whas____d20", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "lut_serverAdapter_cnt_2_whas____d21", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "lut_serverAdapter_cnt_3_whas____d23", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "lut_serverAdapter_s1_0_BIT_0___d51", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "lut_serverAdapter_s1___d50", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "row_num_7_EQ_0___d69", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "state_3_EQ_2___d70", 1u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h9401", 5u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h9405", 5u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h9411", 2u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h9431", 32u);
  vcd_set_clock(sim_hdl, num, __clk_handle_0);
  vcd_write_def(sim_hdl, num++, "x__h964", 26u);
  num = INST_in.dump_VCD_defs(num);
  num = INST_in_fifo.dump_VCD_defs(num);
  num = INST_lut_memory.dump_VCD_defs(num);
  num = INST_lut_serverAdapter_cnt.dump_VCD_defs(num);
  num = INST_lut_serverAdapter_cnt_1.dump_VCD_defs(num);
  num = INST_lut_serverAdapter_cnt_2.dump_VCD_defs(num);
  num = INST_lut_serverAdapter_cnt_3.dump_VCD_defs(num);
  num = INST_lut_serverAdapter_outDataCore.dump_VCD_defs(num);
  num = INST_lut_serverAdapter_outData_deqCalled.dump_VCD_defs(num);
  num = INST_lut_serverAdapter_outData_enqData.dump_VCD_defs(num);
  num = INST_lut_serverAdapter_outData_outData.dump_VCD_defs(num);
  num = INST_lut_serverAdapter_s1.dump_VCD_defs(num);
  num = INST_lut_serverAdapter_s1_1.dump_VCD_defs(num);
  num = INST_lut_serverAdapter_writeWithResp.dump_VCD_defs(num);
  num = INST_out.dump_VCD_defs(num);
  num = INST_out_fifo.dump_VCD_defs(num);
  num = INST_row_num.dump_VCD_defs(num);
  num = INST_state.dump_VCD_defs(num);
  vcd_write_scope_end(sim_hdl);
  return num;
}

void MOD_mkEllBMVM::dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkEllBMVM &backing)
{
  vcd_defs(dt, backing);
  vcd_prims(dt, backing);
}

void MOD_mkEllBMVM::vcd_defs(tVCDDumpType dt, MOD_mkEllBMVM &backing)
{
  unsigned int num = vcd_num;
  if (dt == VCD_DUMP_XS)
  {
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 3u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 1u);
    vcd_write_x(sim_hdl, num++, 5u);
    vcd_write_x(sim_hdl, num++, 5u);
    vcd_write_x(sim_hdl, num++, 2u);
    vcd_write_x(sim_hdl, num++, 32u);
    vcd_write_x(sim_hdl, num++, 26u);
  }
  else
    if (dt == VCD_DUMP_CHANGES)
    {
      if ((backing.PORT_RST_N) != PORT_RST_N)
      {
	vcd_write_val(sim_hdl, num, PORT_RST_N, 1u);
	backing.PORT_RST_N = PORT_RST_N;
      }
      ++num;
      if ((backing.DEF_b__h1362) != DEF_b__h1362)
      {
	vcd_write_val(sim_hdl, num, DEF_b__h1362, 3u);
	backing.DEF_b__h1362 = DEF_b__h1362;
      }
      ++num;
      if ((backing.DEF_lut_serverAdapter_cnt_1_whas____d20) != DEF_lut_serverAdapter_cnt_1_whas____d20)
      {
	vcd_write_val(sim_hdl, num, DEF_lut_serverAdapter_cnt_1_whas____d20, 1u);
	backing.DEF_lut_serverAdapter_cnt_1_whas____d20 = DEF_lut_serverAdapter_cnt_1_whas____d20;
      }
      ++num;
      if ((backing.DEF_lut_serverAdapter_cnt_2_whas____d21) != DEF_lut_serverAdapter_cnt_2_whas____d21)
      {
	vcd_write_val(sim_hdl, num, DEF_lut_serverAdapter_cnt_2_whas____d21, 1u);
	backing.DEF_lut_serverAdapter_cnt_2_whas____d21 = DEF_lut_serverAdapter_cnt_2_whas____d21;
      }
      ++num;
      if ((backing.DEF_lut_serverAdapter_cnt_3_whas____d23) != DEF_lut_serverAdapter_cnt_3_whas____d23)
      {
	vcd_write_val(sim_hdl, num, DEF_lut_serverAdapter_cnt_3_whas____d23, 1u);
	backing.DEF_lut_serverAdapter_cnt_3_whas____d23 = DEF_lut_serverAdapter_cnt_3_whas____d23;
      }
      ++num;
      if ((backing.DEF_lut_serverAdapter_s1_0_BIT_0___d51) != DEF_lut_serverAdapter_s1_0_BIT_0___d51)
      {
	vcd_write_val(sim_hdl, num, DEF_lut_serverAdapter_s1_0_BIT_0___d51, 1u);
	backing.DEF_lut_serverAdapter_s1_0_BIT_0___d51 = DEF_lut_serverAdapter_s1_0_BIT_0___d51;
      }
      ++num;
      if ((backing.DEF_lut_serverAdapter_s1___d50) != DEF_lut_serverAdapter_s1___d50)
      {
	vcd_write_val(sim_hdl, num, DEF_lut_serverAdapter_s1___d50, 2u);
	backing.DEF_lut_serverAdapter_s1___d50 = DEF_lut_serverAdapter_s1___d50;
      }
      ++num;
      if ((backing.DEF_row_num_7_EQ_0___d69) != DEF_row_num_7_EQ_0___d69)
      {
	vcd_write_val(sim_hdl, num, DEF_row_num_7_EQ_0___d69, 1u);
	backing.DEF_row_num_7_EQ_0___d69 = DEF_row_num_7_EQ_0___d69;
      }
      ++num;
      if ((backing.DEF_state_3_EQ_2___d70) != DEF_state_3_EQ_2___d70)
      {
	vcd_write_val(sim_hdl, num, DEF_state_3_EQ_2___d70, 1u);
	backing.DEF_state_3_EQ_2___d70 = DEF_state_3_EQ_2___d70;
      }
      ++num;
      if ((backing.DEF_x__h9401) != DEF_x__h9401)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h9401, 5u);
	backing.DEF_x__h9401 = DEF_x__h9401;
      }
      ++num;
      if ((backing.DEF_x__h9405) != DEF_x__h9405)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h9405, 5u);
	backing.DEF_x__h9405 = DEF_x__h9405;
      }
      ++num;
      if ((backing.DEF_x__h9411) != DEF_x__h9411)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h9411, 2u);
	backing.DEF_x__h9411 = DEF_x__h9411;
      }
      ++num;
      if ((backing.DEF_x__h9431) != DEF_x__h9431)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h9431, 32u);
	backing.DEF_x__h9431 = DEF_x__h9431;
      }
      ++num;
      if ((backing.DEF_x__h964) != DEF_x__h964)
      {
	vcd_write_val(sim_hdl, num, DEF_x__h964, 26u);
	backing.DEF_x__h964 = DEF_x__h964;
      }
      ++num;
    }
    else
    {
      vcd_write_val(sim_hdl, num++, PORT_RST_N, 1u);
      backing.PORT_RST_N = PORT_RST_N;
      vcd_write_val(sim_hdl, num++, DEF_b__h1362, 3u);
      backing.DEF_b__h1362 = DEF_b__h1362;
      vcd_write_val(sim_hdl, num++, DEF_lut_serverAdapter_cnt_1_whas____d20, 1u);
      backing.DEF_lut_serverAdapter_cnt_1_whas____d20 = DEF_lut_serverAdapter_cnt_1_whas____d20;
      vcd_write_val(sim_hdl, num++, DEF_lut_serverAdapter_cnt_2_whas____d21, 1u);
      backing.DEF_lut_serverAdapter_cnt_2_whas____d21 = DEF_lut_serverAdapter_cnt_2_whas____d21;
      vcd_write_val(sim_hdl, num++, DEF_lut_serverAdapter_cnt_3_whas____d23, 1u);
      backing.DEF_lut_serverAdapter_cnt_3_whas____d23 = DEF_lut_serverAdapter_cnt_3_whas____d23;
      vcd_write_val(sim_hdl, num++, DEF_lut_serverAdapter_s1_0_BIT_0___d51, 1u);
      backing.DEF_lut_serverAdapter_s1_0_BIT_0___d51 = DEF_lut_serverAdapter_s1_0_BIT_0___d51;
      vcd_write_val(sim_hdl, num++, DEF_lut_serverAdapter_s1___d50, 2u);
      backing.DEF_lut_serverAdapter_s1___d50 = DEF_lut_serverAdapter_s1___d50;
      vcd_write_val(sim_hdl, num++, DEF_row_num_7_EQ_0___d69, 1u);
      backing.DEF_row_num_7_EQ_0___d69 = DEF_row_num_7_EQ_0___d69;
      vcd_write_val(sim_hdl, num++, DEF_state_3_EQ_2___d70, 1u);
      backing.DEF_state_3_EQ_2___d70 = DEF_state_3_EQ_2___d70;
      vcd_write_val(sim_hdl, num++, DEF_x__h9401, 5u);
      backing.DEF_x__h9401 = DEF_x__h9401;
      vcd_write_val(sim_hdl, num++, DEF_x__h9405, 5u);
      backing.DEF_x__h9405 = DEF_x__h9405;
      vcd_write_val(sim_hdl, num++, DEF_x__h9411, 2u);
      backing.DEF_x__h9411 = DEF_x__h9411;
      vcd_write_val(sim_hdl, num++, DEF_x__h9431, 32u);
      backing.DEF_x__h9431 = DEF_x__h9431;
      vcd_write_val(sim_hdl, num++, DEF_x__h964, 26u);
      backing.DEF_x__h964 = DEF_x__h964;
    }
}

void MOD_mkEllBMVM::vcd_prims(tVCDDumpType dt, MOD_mkEllBMVM &backing)
{
  INST_in.dump_VCD(dt, backing.INST_in);
  INST_in_fifo.dump_VCD(dt, backing.INST_in_fifo);
  INST_lut_memory.dump_VCD(dt, backing.INST_lut_memory);
  INST_lut_serverAdapter_cnt.dump_VCD(dt, backing.INST_lut_serverAdapter_cnt);
  INST_lut_serverAdapter_cnt_1.dump_VCD(dt, backing.INST_lut_serverAdapter_cnt_1);
  INST_lut_serverAdapter_cnt_2.dump_VCD(dt, backing.INST_lut_serverAdapter_cnt_2);
  INST_lut_serverAdapter_cnt_3.dump_VCD(dt, backing.INST_lut_serverAdapter_cnt_3);
  INST_lut_serverAdapter_outDataCore.dump_VCD(dt, backing.INST_lut_serverAdapter_outDataCore);
  INST_lut_serverAdapter_outData_deqCalled.dump_VCD(dt,
						    backing.INST_lut_serverAdapter_outData_deqCalled);
  INST_lut_serverAdapter_outData_enqData.dump_VCD(dt, backing.INST_lut_serverAdapter_outData_enqData);
  INST_lut_serverAdapter_outData_outData.dump_VCD(dt, backing.INST_lut_serverAdapter_outData_outData);
  INST_lut_serverAdapter_s1.dump_VCD(dt, backing.INST_lut_serverAdapter_s1);
  INST_lut_serverAdapter_s1_1.dump_VCD(dt, backing.INST_lut_serverAdapter_s1_1);
  INST_lut_serverAdapter_writeWithResp.dump_VCD(dt, backing.INST_lut_serverAdapter_writeWithResp);
  INST_out.dump_VCD(dt, backing.INST_out);
  INST_out_fifo.dump_VCD(dt, backing.INST_out_fifo);
  INST_row_num.dump_VCD(dt, backing.INST_row_num);
  INST_state.dump_VCD(dt, backing.INST_state);
}
