/*
 * Generated by Bluespec Compiler, version 2014.05.C (build 33930, 2014-05-28)
 * 
 * On Mon Apr 30 21:47:05 IST 2018
 * 
 */

/* Generation options: */
#ifndef __mkTb_h__
#define __mkTb_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkTb module */
class MOD_mkTb : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt8> INST_ad;
  MOD_Reg<tUInt8> INST_state;
  MOD_BRAM<tUInt8,tUInt8,tUInt8> INST_test_memory;
  MOD_Reg<tUInt8> INST_test_serverAdapter_cnt;
  MOD_Wire<tUInt8> INST_test_serverAdapter_cnt_1;
  MOD_Wire<tUInt8> INST_test_serverAdapter_cnt_2;
  MOD_Wire<tUInt8> INST_test_serverAdapter_cnt_3;
  MOD_Fifo<tUInt8> INST_test_serverAdapter_outDataCore;
  MOD_Wire<tUInt8> INST_test_serverAdapter_outData_deqCalled;
  MOD_Wire<tUInt8> INST_test_serverAdapter_outData_enqData;
  MOD_Wire<tUInt8> INST_test_serverAdapter_outData_outData;
  MOD_Reg<tUInt8> INST_test_serverAdapter_s1;
  MOD_Wire<tUInt8> INST_test_serverAdapter_s1_1;
  MOD_Wire<tUInt8> INST_test_serverAdapter_writeWithResp;
 
 /* Constructor */
 public:
  MOD_mkTb(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_x2__h1787;
  tUInt8 DEF_b__h1051;
  tUInt8 DEF_test_serverAdapter_s1___d50;
  tUInt8 DEF_test_serverAdapter_cnt_3_whas____d23;
  tUInt8 DEF_test_serverAdapter_cnt_2_whas____d21;
  tUInt8 DEF_test_serverAdapter_cnt_1_whas____d20;
  tUInt8 DEF_test_serverAdapter_s1_0_BIT_0___d51;
 
 /* Local definitions */
 private:
  tUInt8 DEF_x__h653;
 
 /* Rules */
 public:
  void RL_test_serverAdapter_outData_setFirstCore();
  void RL_test_serverAdapter_outData_setFirstEnq();
  void RL_test_serverAdapter_outData_enqOnly();
  void RL_test_serverAdapter_outData_deqOnly();
  void RL_test_serverAdapter_outData_enqAndDeq();
  void RL_test_serverAdapter_cnt_finalAdd();
  void RL_test_serverAdapter_s1__dreg_update();
  void RL_test_serverAdapter_stageReadResponseAlways();
  void RL_test_serverAdapter_moveToOutFIFO();
  void RL_test_serverAdapter_overRun();
  void RL_sendRequest();
  void RL_receive();
  void RL_complete();
 
 /* Methods */
 public:
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkTb &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkTb &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkTb &backing);
};

#endif /* ifndef __mkTb_h__ */
