//
// Generated by Bluespec Compiler, version 2014.05.C (build 33930, 2014-05-28)
//
// On Tue Apr  3 21:19:46 IST 2018
//
//
// Ports:
// Name                         I/O  size props
// matrix_mul                     O     8
// RDY_matrix_mul                 O     1 const
// CLK                            I     1 unused
// RST_N                          I     1 unused
// matrix_mul_x                   I     4
//
// Combinational paths from inputs to outputs:
//   matrix_mul_x -> matrix_mul
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkModuleDeepThought(CLK,
			   RST_N,

			   matrix_mul_x,
			   matrix_mul,
			   RDY_matrix_mul);
  input  CLK;
  input  RST_N;

  // value method matrix_mul
  input  [3 : 0] matrix_mul_x;
  output [7 : 0] matrix_mul;
  output RDY_matrix_mul;

  // signals for module outputs
  wire [7 : 0] matrix_mul;
  wire RDY_matrix_mul;

  // remaining internal signals
  wire [7 : 0] IF_matrix_mul_x_BIT_0_THEN_4_ELSE_0___d2;
  wire x__h3677, x__h4083;

  // value method matrix_mul
  assign matrix_mul =
	     { x__h4083 ^ matrix_mul_x[3],
	       x__h3677 ^ matrix_mul_x[1],
	       IF_matrix_mul_x_BIT_0_THEN_4_ELSE_0___d2[5] ^ matrix_mul_x[3],
	       IF_matrix_mul_x_BIT_0_THEN_4_ELSE_0___d2[4] ^ matrix_mul_x[1],
	       IF_matrix_mul_x_BIT_0_THEN_4_ELSE_0___d2[3] ^ matrix_mul_x[2],
	       IF_matrix_mul_x_BIT_0_THEN_4_ELSE_0___d2[2:0] } ;
  assign RDY_matrix_mul = 1'd1 ;

  // remaining internal signals
  assign IF_matrix_mul_x_BIT_0_THEN_4_ELSE_0___d2 =
	     matrix_mul_x[0] ? 8'd4 : 8'd0 ;
  assign x__h3677 =
	     IF_matrix_mul_x_BIT_0_THEN_4_ELSE_0___d2[6] ^ matrix_mul_x[0] ;
  assign x__h4083 =
	     IF_matrix_mul_x_BIT_0_THEN_4_ELSE_0___d2[7] ^ matrix_mul_x[2] ;
endmodule  // mkModuleDeepThought

